### ISSUE TITLE
a small bug found in use

### ISSUE THREAD

**Issue by NorthOrange** [SirVer/ultisnips#1135] opened 2019-11-08 17:04 UTC
In the file format used by the vimwiki plugin, this plugin will be invalid. For example
If my vimwiki is set:
Let g:vimwiki_list = [{'path': '~/vimwiki/',
                       \ 'syntax': 'markdown', 'ext': '.md'}]
I can't use ultisnips in the .md file.

After I found the error, I decided not to use vimwiki, so I deleted it and forgot to record the error. I am very sorry.

**Comment by SirVer** [comment] 2019-11-09 07:16
I am not sure what the problem is here, since there is no repro case. I assume though that vimwiki does some something to overwrite UltiSnips key bindings. It sounds like a bug in vimwiki then, so I'll close this as nonactionable for UltiSnips until I understand better what UltiSnips should be doing differently.

**Closed by SirVer** 2019-11-09 07:16 UTC

**Comment by Nealium** [comment] 2023-05-12 16:45
Old + Closed Issue, but adding context for anybody in the future.

VimWiki buffers actually have the filetype `vimwiki`, even in markdown mode, this is so their VimWiki specific bindings aren't applied in **every** markdown file. UltiSnips seems to go off filetype **not** extension. It makes no sense for UltiSnips to show markdown snippets in vimwiki buffers by default, as VimWiki's default is their own syntax.

So **the solution** is to create a file: `~/.vim/ftplugin/vimwiki.vim` and add:
```vim
call UltiSnips#AddFiletypes("markdown")
```

@NorthOrange I do recommend giving VimWiki another try, if you haven't found another solution, it's quite good!
