### ISSUE TITLE
Error trying to expand PHP class snippet templates

### ISSUE THREAD

**Issue by ltgouvea** [SirVer/ultisnips#1136] opened 2019-11-09 04:32 UTC
**Expected behavior:**
Ultisnips expands the class/trait/interface/etc snippet template and allows editing correctly.

**Actual behavior:**
The snippet gets expanded, but the following error pops up (traceback running VIM from the image accessed via `make repro`):
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/src/UltiSnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/src/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 127, in expand
    if not self._try_expand():
  File "/src/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 759, in _try_expand
    self._do_snippet(snippet, before)
  File "/src/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 712, in _do_snippet
    text_before, self._visual_content, parent, start, end
  File "/src/UltiSnips/pythonx/UltiSnips/snippet/definition/base.py", line 488, in launch
    snippet_instance.update_textobjects(vim_helper.buf)
  File "/src/UltiSnips/pythonx/UltiSnips/text_objects/snippet_instance.py", line 93, in update_textobjects
    if obj._update(done, buf):
  File "/src/UltiSnips/pythonx/UltiSnips/text_objects/python_code.py", line 269, in _update
    exec(code, self._locals)  # pylint:disable=exec-used
  File "<string>", line 2, in <module>
  File "/usr/local/lib/python3.6/posixpath.py", line 457, in relpath
    raise ValueError("no path specified")
ValueError: no path specified

Executed snippet code:
  1
  2   relpath = os.path.relpath(path)
  3   m = re.search(r'[A-Z].+(?=/)', relpath)
  4   if m:
  5     snip.rv = m.group().replace('/', '\\')
  6
```

**Steps to reproduce**

1. open a new file
2. `:set ft=php`
3. type `class` and press `<tab>` to expand

-----

- **Operating System**: Linux Mint 19 
- **Vim Version**: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  9 2019 04:16:27)
Included patches: 1-586

- **UltiSnips Version**: `74dae03d02183b4416e2a3f8a80b69fefc2e5aee` 
- **Python inside Vim**: 3.6.9 
- **Docker repo/vimrc**: no additional config was needed

**Comment by SirVer** [comment] 2019-11-09 07:14
`raise ValueError("no path specified")` is the problem here: a new file has no path, since it was never saved to disk. So this variable is undefined, but it is used in the snippet. Workaround: save the empty file first, then expand the snippet. Or alternatively fix the snippet to use a dummy name if path is not set: `os.path.relpath(path or "new_file")`.

Closing as this is not a bug in UltiSnips the engine. It could be considered a bug in https://github.com/honza/vim-snippets and should then be reported there.

**Closed by SirVer** 2019-11-09 07:14 UTC
