### ISSUE TITLE
Running `UltiSnipsEdit` won't open on the default directory

### ISSUE THREAD

**Issue by chris-fa** [SirVer/ultisnips#798] opened 2016-12-01 05:04 UTC
### Context
I'm inside a PHP file and run `:UltiSnipsEdit` and then `:w`. 

### Expected behavior
It saves to `~/.vim/UltiSnips/php.snippets`

### Actual Behaviour
Saves to `UltiSnips/php.snippets` inside the project directory

### Miscellaneous
* My `~/.vim` folder is a soft symbolic link to the actual location. 
* The directory `~/.vim/UltiSnips` exists.

**Comment by dkrmr** [comment] 2016-12-16 08:41
Same here.

**Comment by Sathors** [comment] 2017-01-12 14:25
Seems to be a duplicate of #709.

**Comment by andreyorst** [comment] 2018-04-06 09:58
related to #711

**Closed by andreyorst** 2018-04-06 09:58 UTC
