### ISSUE TITLE
Have to Press g:UltiSnipsListSnippets Twice to Get List

### ISSUE THREAD

**Issue by cabellicar123** [SirVer/ultisnips#566] opened 2015-09-07 01:36 UTC
I have `g:UltiSnipsListSnippets` set to `<f2>`. When in insert mode on a non-whitespace character pressing `<f2>` first inserts a tab and then on a second press actually lists out all the snippets (due to it now being on a space. When on a whitespace character this works as expected. Is there a reason for this?

**Comment by SirVer** [comment] 2015-09-07 06:50
Very unlikely that this is due to ultisnips. Check `:verbose imap <F2>` and see what it is mapped too. Then try to disable all plugins but UltiSnips and see if the problem persists. Also try in a gui client (gvim) instead of on the terminal.

**Comment by cabellicar123** [comment] 2015-09-08 02:55
Output is:
```
i  <F2>        * <C-R>=UltiSnips#ListSnippets()<CR>
        Last set from ~/.vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
```
After disabling all other plugins the same behavior exists.

**Comment by SirVer** [comment] 2015-09-08 05:13
I cannot repro still. It works perfectly for me in the gui and on terminal.

Can you make a minimal vimrc available that shows this problem for you?

**Comment by cabellicar123** [comment] 2015-09-09 21:19
Here is a minimal vimrc which has the issue for me:
```
set nocompatible
filetype off

" set the runtime path to include NeoBundle and initialize
set runtimepath+=~/.vim/bundle/neobundle.vim/

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'SirVer/ultisnips'

call neobundle#end()

filetype plugin indent on

NeoBundleCheck

let g:UltiSnipsListSnippets="<f2>"
```
Note here rather than add extra whitespace pressing `<f2>` either works or does nothing depending on the whitespace present.

**Comment by SirVer** [comment] 2015-09-10 04:51
Thanks, I'll try to repro probably tomorrow. This is on Linux, right?

**Comment by cabellicar123** [comment] 2015-09-10 22:57
Yes on Arch Linux with Terminator

**Comment by SirVer** [comment] 2015-09-14 12:46
I cannot reproduce this. On a new user, ubuntu linux, these are the steps I took:

```
$ curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh > install.sh
$ sh install.sh
$ vi ~/.vimrc 
<paste in your minimal vimrc>
restart vim a couple of times till neobundle was happy.
$ mkdir -p ~/.vim/UltiSnips
$ vim ~/.vim/UltiSnips/all.snippets
edit for this content:
snippet lorem
lorem ipsum
endsnippet
$ vim /tmp/blub.all
<press f2> -> lists snippets immediately.
```

Please see if you can reproduce with the exact same steps. I believe it is probably something in your terminal emulator that interferes here. I am closing for now, I am unconvinced that UltiSnips is too blame. I will further investigate if you disagree.

**Closed by SirVer** 2015-09-14 12:46 UTC
