### ISSUE TITLE
Snips not expanding after installing with vim-plug

### ISSUE THREAD

**Issue by Hotrider** [SirVer/ultisnips#1068] opened 2019-03-21 21:07 UTC
I installed Ultisnips using vim-plug and it is not working at all.  Any help would be greatly appreciated.

Here is my `~/.vimrc ` file:

```
  1 set number
  2 
  3 " Call the .vimrc.plug file"
  4  if filereadable(expand("~/.vimrc.plug"))
  5      source ~/.vimrc.plug
  6  endif
  7 
```
My `~/.vimrc.plug` file looks like this:

```
 1 call plug#begin('~/.vim/plugged')
  2 
  3 "Fugitive Vim Github Wrapper
  4 Plug 'lervag/vimtex'
  5 let g:tex_flavor='latex'
  6 let g:vimtex_view_method='zathura'
  7 let g:vimtex_quickfix_mode=0
  8 set conceallevel=1
  9 let g:tex_conceal='abdmg'
 10 
 11 
 12 Plug 'sirver/ultisnips'
 13 let g:UltiSnipsExpandTrigger = '<tab>'
 14 let g:UltiSnipsSnippetDirectories = ['~/.vim/UltiSnips/' , 'Ultisnips']
 15 let g:UltiSnipsJumpForwardTrigger = '<tab>'
 16 let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
 17 let g:UltiSnipsEditSplit="vertical"
 18 call plug#end()

```

**Comment by axelf4** [comment] 2019-03-22 09:44
Had a similar experience yesterday. Running `:UltiSnipsEdit` created a snippet file and directory in `~/UltiSnips/....snippets` instead of `~/.vim/UltiSnips/....snippets`. Snippets weren't working and `:call UltiSnips#RefreshSnippets()` only echoed `0`. `~/UltiSnips` was not in `&rtp` . This was after installing via vim-plug and (I think) restarting Vim.
Moving the snippets file to the correct directory resolved the issue and `:UltiSnipsEdit` started opening the correct file.

Output of `:PlugSnapshot`: `silent! let g:plugs['ultisnips'].commit = '6fdc364'`.

Vim version:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan  3 2019 13:15:26)
Inkluderade patchar: 1-682
```

**Comment by Hotrider** [comment] 2019-03-22 13:46
I had already moved Ultisnips to `~/.vim/Ultisnips/ `using `UltiSnipsSnippetDirectories` in the `./vimrc.plug` file. So I guess that wasn't my problem. However, `:call Ultisnips#RefreshSnippets()` do not give any value. It just puts the buffer back in the text file.

**Comment by lauritzvanluijk** [comment] 2019-03-22 16:34
have you tried installing `honza/vim-snippets `? Do those snippets work for you (for example `ife<tab>`)? Does it not work in `.vim` files either?

**Comment by Hotrider** [comment] 2019-03-22 17:22
I installed `honza/vim-snippets` . The snipets works  in .vim files but not in other files (say in .tex files )

**Comment by lauritzvanluijk** [comment] 2019-03-22 20:43
well same for me... the `tex.snippets` from `honza/vim-snippets` work though. To just copy your snippets into that file is at least a workaround. If you find a solution I'd be happy to hear it

**Comment by Hotrider** [comment] 2019-03-23 10:46
I believe this is not a workaround. This is just using snippets from `honza/vim-snippets/snippets/tex.snippets`. We can not use tools from `ultisnips` in those snippets

**Comment by smancill** [comment] 2019-04-02 17:57
Seems probably related to #711.

**Comment by qjcg** [comment] 2019-05-06 16:56
Having the same issue, and agree with @smancill that it looks related to #711 --- frustrating, because that issue has been open for 3 years!

**Comment by SirVer** [comment] 2019-10-30 20:03
> I installed honza/vim-snippets . The snipets works in .vim files but not in other files (say in .tex files )

This sounds phony to me, and probably makes this unrelated to #711. However, I cannot reproduce the problem OP is describing (I need a video or something, exactly what you are typing and seeing).

**Comment by SirVer** [comment] 2019-11-19 20:02
Closing since no further information was provided and I cannot reproduce.

**Closed by SirVer** 2019-11-19 20:02 UTC
Labels: pending feedback
