### ISSUE TITLE
In-word expansion with method chaining not showing up

### ISSUE THREAD

**Issue by karanr** [SirVer/ultisnips#479] opened 2015-04-09 19:53 UTC
I was looking to use in-word expansions when chaining methods, for example:
snippet collif "{|e| $1 if $2 }" i
collect {|e| $1 if $2 }
endsnippet
The snippet shows up in YCM and UltiSnipsListSnippets, and can be expanded when the trigger collif is part of any word, typed on its own, or preceded by any special character. However if the trigger is part of a chain like User.collif the snippet does not show up in either YCM or Ultisnips list nor can it be expanded.

I came across issue https://github.com/SirVer/ultisnips/issues/177
Using with regular expression 
snippet "\.collif" "{|e| $1 if $2 }" r
.collect {|e| $1 if $2 }
endsnippet
The snippet expands on trigger but does not show up in YCM list, it shows up in Ultisnips list only with entire trigger input (User.collif<c-tab>).
I understand that this might be a YCM issue or my lack of understanding of the correct usage of the plugin and its option. I looked up issues open and closed on both ultisnips and YCM repos and came across https://github.com/Valloric/YouCompleteMe/issues/421 and hence am posting this here.

**Comment by SirVer** [comment] 2015-04-13 18:54
>  However if the trigger is part of a chain like User.collif the snippet does not show up in either YCM or Ultisnips list nor can it be expanded.

Cannot repro that. It does not show up in YCM, but it can certainly be expanded. 

I do not understand the rest of the bug report. What is it that you expect to work but doesn't?

**Comment by karanr** [comment] 2015-04-14 07:22
1. I expected it to show up in YCM, "YCM uses ultisnips internal UltiSnips_Manager._snips()", so if there was a way for it to show up.
or 
2. It should appear in the UltiSnips list without having to type the entire trigger. At present the only way for it to show in the list is .collif<C-Tab> which is redundant because one would expand it at that point instead of going to the UltiSnips list. Ability to view .collif in the UltiSnips list when .c<C-Tab> or .co<C-Tab> is pressed would be perfect. At present .c<C-Tab> .co<C-Tab> shows other triggers that start with .c or .co but not .collif 
or 
3. The expansion would occur with incomplete trigger ( .col<C-j> ) if there are no other triggers like .column etc that use the same starting letters.

Point 2, having it appear in the UltiSnips completion list when .c<C-Tab> is pressed would be ideal.

**Comment by SirVer** [comment] 2015-04-14 18:49
So you found that list snippets does not show all partial matches? That is related to https://github.com/SirVer/ultisnips/issues/177, but should be fixable for inword snippets. Then it should also show up in for YCM. Do you want to attempt a fix?

**Comment by SirVer** [comment] 2015-07-11 16:43
Closing as dupe of #177.

**Closed by SirVer** 2015-07-11 16:43 UTC
