### ISSUE TITLE
Ultisnip keep display error while typing

### ISSUE THREAD

**Issue by duytrung** [SirVer/ultisnips#1290] opened 2020-11-03 11:42 UTC
Hello,

I use vim to compose a c source file but ended up with bunch of error. 

**Expected behavior:**

**Actual behavior:**
Displaying errors such as this:

```
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue


```

**Steps to reproduce**
Using vim to compose a c source such as: vim HelloWorld.c

- **Operating System**: Windows 10
- **Vim Version**: 
```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 25 2020 11:44:06)
Included patches: 1-1895
Compiled by <https://www.msys2.org/>
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               +ruby/dyn          +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim82"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -I/usr/include/ncursesw  -march=x86-64 -mtune=generic -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -pipe -fstack-protector-strong -pipe -Wl,--as-needed -o vim.exe        -lm   -lncursesw -liconv -lacl -lintl   -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -ldl -lcrypt

```

- **UltiSnips Version**: latest - update according to Evervim Update
- **Python inside Vim**: 
```
$ python --version
Python 3.8.6
```

- **Docker repo/vimrc**: 
I use vim in Msys2 distribution.

Thanks for consider the issue

**Comment by gorrioncillo** [comment] 2020-12-06 18:03
I fix my similar problem changing the following settings in my ~/.vimrc (assuming your plugin UltiSnips is on ~/.vim/pack/plugins/start)
I have to mention that my vim is from git-bash (the vim which comes with git for windows) and have support for python but dinamically (+python/dyn) and i have to put `set pythonthreedll=python37.dll` on top of my .vimrc (note I have python 3.7.2 installed).

` 
py3 import sys
`
`
py3 sys.path.append('C:\\Users\\[YOURUSERNAME]\\.vim\\pack\\plugins\\start\\ultisnips\\pythonx')
`
I do this because my path could not search for that especific folder, especially "pythonx/" which is where the .py files resides. I do not know why my python did not recognize that folder.

`
set runtimepath+=~/.vim/pack/plugins/start/ultisnips
`
This is because the instructions [doc](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt) says for installing from a package (I installed the last release, I do not clon the repo).

`
let g:UltiSnipsSnippetDirectories=["C:\\Users\\[YOURUSERNAME]\\.vim\\pack\\plugins\\start\\vim-snippets\\UltiSnips"]
`
and this fix my problem with missing the directory where my snippets are, in my case i use [vim-snippets](https://github.com/honza/vim-snippets)

One thing that I could not fix was the `:UltiSnipsEdit` which cannot open the .snippet file i want to modify.

I use windows 10 version 1909
vim 8.2 Compiled by <https://www.msys2.org/>
UltiSnips 3.2 release

**Comment by mkreim** [comment] 2021-01-16 13:05
Hello, 

I think I see the same or a similar error and have so far no idea how to deal with it.

Currently I Installed ultisnips into `~/.vim/pack/pluginRepos/opt/ultisnips` (I moved it to opt as I cannot use ultisnips at the moment). If i load it with `:packadd ultisnips`, go to edit mode and write a single letter I get these messages:

```
Fehler beim Ausführen von "InsertCharPre Autokommandos für "*"..script /home/x/.vim/pack/pluginRepos/opt/ultisnips/autoload/UltiSnips.vim":
Zeile    8:
Traceback (most recent call last):
Fehler beim Ausführen von "InsertCharPre Autokommandos für "*"..script /home/x/.vim/pack/pluginRepos/opt/ultisnips/autoload/UltiSnips.vim":
Zeile    8:
  File "/home/x/bin/pyenv/versions/3.8.7/lib/python3.8/subprocess.py", line 64, in <module>
Fehler beim Ausführen von "InsertCharPre Autokommandos für "*"..script /home/x/.vim/pack/pluginRepos/opt/ultisnips/autoload/UltiSnips.vim":
Zeile    8:
    import msvcrt
Fehler beim Ausführen von "InsertCharPre Autokommandos für "*"..script /home/x/.vim/pack/pluginRepos/opt/ultisnips/autoload/UltiSnips.vim":
Zeile    8:
ModuleNotFoundError: No module named 'msvcrt'
Fehler beim Ausführen von "InsertCharPre Autokommandos für "*"..script /home/x/.vim/pack/pluginRepos/opt/ultisnips/autoload/UltiSnips.vim":
Zeile    8:
Fehler beim Ausführen von "InsertCharPre Autokommandos für "*"..script /home/x/.vim/pack/pluginRepos/opt/ultisnips/autoload/UltiSnips.vim":
Zeile    8:
During handling of the above exception, another exception occurred:
Fehler beim Ausführen von "InsertCharPre Autokommandos für "*"..script /home/x/.vim/pack/pluginRepos/opt/ultisnips/autoload/UltiSnips.vim":
Zeile    8:
Fehler beim Ausführen von "InsertCharPre Autokommandos für "*"..script /home/x/.vim/pack/pluginRepos/opt/ultisnips/autoload/UltiSnips.vim":
Zeile    8:
Traceback (most recent call last):
Fehler beim Ausführen von "InsertCharPre Autokommandos für "*"..script /home/x/.vim/pack/pluginRepos/opt/ultisnips/autoload/UltiSnips.vim":
Zeile    8:
  File "<string>", line 1, in <module>
Fehler beim Ausführen von "InsertCharPre Autokommandos für "*"..script /home/x/.vim/pack/pluginRepos/opt/ultisnips/autoload/UltiSnips.vim":
Zeile    8:
  File "/home/x/.vim/pack/pluginRepos/opt/ultisnips/pythonx/UltiSnips/__init__.py", line 6, in
<module>
Fehler beim Ausführen von "InsertCharPre Autokommandos für "*"..script /home/x/.vim/pack/pluginRepos/opt/ultisnips/autoload/UltiSnips.vim":
Zeile    8:
    from UltiSnips.snippet_manager import UltiSnips_Manager
Fehler beim Ausführen von "InsertCharPre Autokommandos für "*"..script /home/x/.vim/pack/pluginRepos/opt/ultisnips/autoload/UltiSnips.vim":
Zeile    8:
  File "/home/x/.vim/pack/pluginRepos/opt/ultisnips/pythonx/UltiSnips/snippet_manager.py", line
 13, in <module> 
```

The error appeared after I updated vim and all my plugins to the latest version:
```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12 kompiliert am Jan 16 2021 13:32:05)
Inklusive der Patches: 1-2359
Übersetzt von x
Riesige Version mit GTK2 GUI.
 Ein- (+) oder ausschließlich (-) der Eigenschaften:
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             +sound             -xfontset
-ebcdic            +mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       +xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
          System-vimrc-Datei: "$VIM/vimrc"
        Benutzer-vimrc-Datei: "$HOME/.vimrc"
 zweite Benutzer-vimrc-Datei: "~/.vim/vimrc"
         Benutzer-exrc-Datei: "$HOME/.exrc"
         System-gvimrc-Datei: "$VIM/gvimrc"
       Benutzer-gvimrc-Datei: "$HOME/.gvimrc"
zweite Benutzer-gvimrc-Datei: "~/.vim/gvimrc"
      defaults Datei: "$VIMRUNTIME/defaults.vim"
           System-Menü-Datei: "$VIMRUNTIME/menu.vim"
     Voreinstellung für $VIM: "~/bin/vim8/share/vim"
Übersetzt: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linken: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux -lcanberra -lacl -lattr -lgpm -ldl -L/home/mkreim/bin/pyenv/versions/3.8.7/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm 
```
```
$ python --version
Python 3.8.7

$ uname -a
Linux netsyno-mk 5.8.0-36-generic #40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ cat /proc/version
Linux version 5.8.0-36-generic (buildd@lgw01-amd64-027) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021
```

I tried to google it but I only find people that had python 2 and 3 enabled at the same time or no python at all.
`has("python")` gives me a `0` while `has("python3")` gives me a `1` .

Sadly, @gorrioncillo's idea of setting `set runtimepath+=~/.vim/pack/pluginRepos/opt/ultisnips` did not help me. It only activated the problem without explicitly calling ultisnips via `packadd`.

So if any ideas come up here, I would really be happy. Thanks a lot.

**Comment by TamaMcGlinn** [comment] 2021-03-26 08:02
I had this error, and although `has("python3")` gave a 1, I spotted in `:CheckHealth` that the reported version for python3 was actually 2.7.something ! Just one more thing to check. I solved it as suggested in CheckHealth's warning, by adding to .vimrc:

```
let g:python3_host_prog = "/usr/bin/python3"
```

**Comment by newptcai** [comment] 2021-11-28 12:11
I have the same problem with WSL (Windows Subsystem for Linux). But I am using vim install of neovim.

**Comment by SirVer** [comment] 2021-11-29 15:21
Looking through the longer traceback, what jumps out to me is 

```
ModuleNotFoundError: No module named 'msvcrt'
```

This does not seem to be an UltiSnips issue, it is very likely something is broken with your Python installation or at least with the python that is used within your Vim. Very hard to debug from here.... But I am nearly certain that this is not ultisnips specific, it is just triggered by UltiSnips.

**Comment by kgust** [comment] 2021-11-30 21:22
I had this issue on my MacBook. Turns out the native `vim` was first in my path and it doesn't have python support. I changed my path so the version I installed came first. Now it works!

**Comment by hl037** [comment] 2021-12-04 23:41
Maybe 
`:pyx import sys; print(sys.version)` could help ?

**Comment by newptcai** [comment] 2021-12-08 21:56
@hl037 I tried what you wrote. And I got
```
3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0]
```
Nothing seems suspicious.

**Comment by hl037** [comment] 2021-12-09 00:06
> @hl037 I tried what you wrote. And I got
> 
> ```
> 3.8.10 (default, Sep 28 2021, 16:10:42)
> [GCC 9.3.0]
> ```
> 
> Nothing seems suspicious.

@newptcai Could you provide the traceback you get ? (I mean, there are already 2 different traceback, yours may be actually different, and the first Op didn't say if it is fixed for him or not).

If it's some "couldn't find [...]" error, you could try gorrioncillo's solution

**Comment by newptcai** [comment] 2021-12-10 23:26
@hl037 How do I get a copy of traceback?

**Comment by hl037** [comment] 2021-12-11 12:28
copy paste whate message vims throws you when there are error.
Normally, `:verbose :messages` should work

**Comment by SirVer** [comment] 2022-01-23 20:37
@newptcai Without the traceback, there is not much actionable we can do here. Could you provide it please?

**Comment by newptcai** [comment] 2022-01-24 08:26
OK. I will do it today.

**Comment by newptcai** [comment] 2022-01-24 09:28
~~~
coc.nvim] TexLab Server Started
Error detected while processing InsertCharPre Autocommands for "*"..script /mnt/c/linux/linux/vim/plugged/ultisnips/autoload/UltiSnips.vim:
line    8:
Traceback (most recent call last):
Error detected while processing InsertCharPre Autocommands for "*"..script /mnt/c/linux/linux/vim/plugged/ultisnips/autoload/UltiSnips.vim:
line    8:
  File "<string>", line 1, in <module>
Error detected while processing InsertCharPre Autocommands for "*"..script /mnt/c/linux/linux/vim/plugged/ultisnips/autoload/UltiSnips.vim:
line    8:
  File "/home/xin/.vim/plugged/ultisnips/pythonx/UltiSnips/__init__.py", line 6, in <module>
Error detected while processing InsertCharPre Autocommands for "*"..script /mnt/c/linux/linux/vim/plugged/ultisnips/autoload/UltiSnips.vim:
line    8:
    from UltiSnips.snippet_manager import UltiSnips_Manager
Error detected while processing InsertCharPre Autocommands for "*"..script /mnt/c/linux/linux/vim/plugged/ultisnips/autoload/UltiSnips.vim:
line    8:
  File "/home/xin/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 14, in <module>
Error detected while processing InsertCharPre Autocommands for "*"..script /mnt/c/linux/linux/vim/plugged/ultisnips/autoload/UltiSnips.vim:
line    8:
    from UltiSnips import err_to_scratch_buffer
Error detected while processing InsertCharPre Autocommands for "*"..script /mnt/c/linux/linux/vim/plugged/ultisnips/autoload/UltiSnips.vim:
line    8:
ImportError: cannot import name 'err_to_scratch_buffer' from partially initialized module 'UltiSnips' (most likely due to a circular import) (/home/xi
n/.vim/plugged/ultisnips/pythonx/UltiSnips/__init__.py)
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Error detected while processing TextChangedI Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Error detected while processing TextChangedI Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing TextChangedI Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
E78: Unknown mark
~~~

**Comment by SirVer** [comment] 2022-01-24 13:37
```
ImportError: cannot import name 'err_to_scratch_buffer' from partially initialized module 'UltiSnips' (most likely due to a circular import) (/home/xi
```

I believe this hints that your python installation is not completely healthy. I doubt that this problem is caused by UltiSnips, I just think it is surfacing it. Can can try the following: Uninstall UltiSnips first, then copy the pythonx folder from UltiSnips into your Vim dotfile directory (not sure where that is on Windows though). Then launch Vim and run `:py3 from UltiSnips.snippet_manager import UltiSnips_Manager`. This should give you an error, please provide this one.

**Comment by SirVer** [comment] 2022-02-05 19:58
Closing this as 3rd party problem. Feel free to ask further questions and I can reopen.

**Closed by SirVer** 2022-02-05 19:58 UTC
Labels: pending feedback, windows only, can't reproduce, thirdparty problem

**Comment by jingwen-yang-yjw** [comment] 2022-05-20 04:20
I had the same error on centos7. 
When I launch Vim and run  :py3 from UltiSnips.snippet_manager import UltiSnips_Manager, there is an error as following.
    ImportError: dynamic module does not define module export function (PyInit__posixsubprocess) 

Then I solved this issue by the following steps.

STEP 1:
$ python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/opt/rh/devtoolset-7/root/usr/lib64/python2.7/site-packages', '/opt/rh/devtoolset-7/root/usr/lib/python2.7/site-packages', '/home/gpadmin/gpdb6_bin/lib/python', '/usr/lib64/python36.zip', '/usr/lib64/python3.6', '/usr/lib64/python3.6/lib-dynload', '/usr/local/lib64/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']

STEP 2:
Adding “export PYTHONPATH = /usr/local/lib/python3.6/site-packages:/usr/lib/python3.6/site-packages” to ~/.bash_profile.
And run command in bash "source ~/.bash_profile".

**Comment by w-A-L-L-e** [comment] 2022-09-10 17:48
Had same issue. It works fine with neovim/nvim but not with old vim. So I patched ultisnips to detect this and then not break my legacy vim editor:
Basically added 2 checks for neovim and exit so that it doesn't autoload.

```
diff --git a/autoload/UltiSnips.vim b/autoload/UltiSnips.vim
index 7593392..b31b43d 100644
--- a/autoload/UltiSnips.vim
+++ b/autoload/UltiSnips.vim
@@ -1,6 +1,12 @@
 if exists("b:did_autoload_ultisnips")
     finish
 endif
+
+if !has('nvim')
+  echo "ultisnips is not compatible"
+  finish
+endif
+
 let b:did_autoload_ultisnips = 1
 
 " Also import vim as we expect it to be imported in many places.
diff --git a/plugin/UltiSnips.vim b/plugin/UltiSnips.vim
index 3cdcb5e..b70f007 100644
--- a/plugin/UltiSnips.vim
+++ b/plugin/UltiSnips.vim
@@ -1,6 +1,9 @@
 if exists('did_plugin_ultisnips') || &cp
     finish
 endif
+if !has('nvim')
+    finish
+endif
 let did_plugin_ultisnips=1
 
 if version < 800
(END)
```

**Comment by SirVer** [comment] 2022-10-11 07:50
Many users use Ultisnips with neovim. I just do not test it with it and I do not look into bugs only affecting neovim. So disabling seems overkill to me - something else seems borked in your configuration.

**Comment by themightyoarfish** [comment] 2023-06-12 10:35
I had this issue on Ubuntu 20.04 with some user-installed python version. Removing that and using the `apt` packages for python 3 and building against that makes the errors go away.

**Comment by AnthonyAwuley-GBI** [comment] 2023-12-16 05:33
reinstall vim if you are on mac

**Comment by Brannua** [comment] 2025-04-06 03:58
if you are on mac m1, try`brew uninstall vim`, then execute `brew install macvim`.
