### ISSUE TITLE
Sierra OSX

### ISSUE THREAD

**Issue by xavierartot** [SirVer/ultisnips#843] opened 2017-04-16 16:57 UTC
I installed Vim in Sierra with a "MacBook Pro (13-inch, 2016".

- each time I'm using, i,a,o I have those error...

```Error detected while processing function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
```

**Comment by Cheezmeister** [comment] 2017-05-15 17:39
Possible dupe of #823

**Comment by andreyorst** [comment] 2018-04-07 09:44
Duplicate of #823

**Closed by andreyorst** 2018-04-07 09:44 UTC
