### ISSUE TITLE
UltiSnips.vim error

### ISSUE THREAD

**Issue by jhbatley8** [SirVer/ultisnips#1107] opened 2019-10-12 03:05 UTC
Hello, I'm new to Vim plugins and UltiSnips. I've been working on trying to use the plugin now for several hours with no success. 
**Expected behavior:**
For the file `/home/jhbatley/.vim/plugged/ultisnips/plugin/UltiSnips.vim` to integrate into the plugin correctly

**Actual behavior:**
Output of running `vim`:
`Error detected while processing /home/jhbatley/.vim/plugged/ultisnips/plugin/UltiSnips.vim:
line   45:
E10: \ should be followed by /, ? or &`

Current `.vimrc` file:
```
set encoding=utf-8                                                         
                                                                                
syntax enable                                                                   
                                                                                
call plug#begin('~/.vim/plugged')                                               
Plug 'lervag/vimtex'                                                            
Plug 'SirVer/ultisnips'                                                         
call plug#end()                                                                 
                                                                                
let g:UltiSnipsExpandTrigger = '<tab>'                                          
let g:UltiSnipsJumpForwardTrigger = '<tab>'                                     
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'                                  
let g:UltiSnipsSnippetsDir="/home/jhbatley/.vim/UltiSnips"                      
let g:tex_flavor='latex'                                                        
let g:vimtex_quickfix_mode=0                                                    
set conceallevel=1                                                              
let g:tex_conceal='abdmg'                                                       
                                                                                
set colorcolumn=80                                                              
setlocal spell                                                                  
set spelllang=en_us                                                             
                                                                                
syntax on                                                                       
set syntax=tex                                                                  
set backspace=indent,eol,start
```

- **Operating System**: 
Ubuntu 18.04
- **Vim Version**: 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 11 2019 21:08:09)
Included patches: 1-2136
```

- **UltiSnips Version**: 
I'm assuming the version of UltiSnips is the latest version. I cloned the repository today. 
- **Python inside Vim**: 
`:py import sys; print(sys.version)` output:
```
2.7.15+ (default, Oct  7 2019, 17:39:04)
[GCC 7.4.0]
```
`:py3 import sys; print(sys.version)` output:
`E319: Sorry, the command is not available in this version`

- **Docker repo/vimrc**: 
Unknown

**Comment by SirVer** [comment] 2019-10-20 19:19
I believe you accidentally edited the file that throws the error, because the syntax is definitiely correct. Did you try `rm -rf ~/.vim/plugged` and try again? If the problem persist, zip up your bundle directory & your vim config for inspection, so far this is not reproducible.

Also, this `let g:UltiSnipsSnippetsDir="/home/jhbatley/.vim/UltiSnips"` will not have the desired effect without setting other variables as well. Read through: https://github.com/SirVer/ultisnips/blob/8ff301c651d6df806c0f9305273a6c62a693bc48/doc/UltiSnips.txt#L524

Closing until

**Closed by SirVer** 2019-10-20 19:19 UTC
