### ISSUE TITLE
Ultisnips tab completion is not working.

### ISSUE THREAD

**Issue by collegeimprovements** [SirVer/ultisnips#512] opened 2015-06-09 13:15 UTC
I followed yours and Drew Neil's Screencast tutorial.
Somehow I'm not able to expand snippets with tab completion or by any other way.
However everything else seems fine. I get `:UltiSnipsEdit` commands and it opens a new snippet-file for that filetype. But by somehow I'm not able to get those snippets expanded in vim.
I'm using `macvim version: 7.4.712`.

Here is my full .vimrc file.
```viml
set nocompatible
"***************************** NeoBundleSetup ***********************
"NeoBundle Scripts-----------------------------
if has('vim_starting')
  if &compatible
    set nocompatible               " Be iMproved
  endif

  " Required:
  set runtimepath+=/Users/arpit/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('/Users/arpit/.vim/bundle'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" Add or remove your Bundles here:

NeoBundle 'AndrewRadev/splitjoin.vim'
NeoBundle 'marijnh/tern_for_vim'
NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'Raimondi/delimitMate'
NeoBundle 'Shougo/neosnippet-snippets'
NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'SirVer/ultisnips'
NeoBundle 'amix/vim-zenroom2'
NeoBundle 'xolox/vim-misc'
NeoBundle 'xolox/vim-notes'
NeoBundle 'bling/vim-airline'
NeoBundle 'bling/vim-bufferline'
NeoBundle 'ctrlpvim/ctrlp.vim'
NeoBundle 'flazz/vim-colorschemes'
NeoBundle 'honza/vim-snippets'
NeoBundle 'junegunn/goyo.vim'
NeoBundle 'junegunn/vim-easy-align'
NeoBundle 'mattn/emmet-vim'
NeoBundle 'mattn/gist-vim', {'depends': 'mattn/webapi-vim'}
NeoBundle 'matze/vim-move'
NeoBundle 'powerline/powerline'
NeoBundle 'rking/ag.vim'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'ryanoasis/vim-webdevicons'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'sjl/gundo.vim'
NeoBundle 'terryma/vim-multiple-cursors'
NeoBundle 'ryanoasis/vim-webdevicons'
NeoBundle 'tomtom/tcomment_vim'
NeoBundle 'tpope/vim-endwise'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'tpope/vim-rails'
NeoBundle 'tpope/vim-sensible'
NeoBundle 'tpope/vim-surround'
NeoBundle 'tpope/vim-vinegar'
NeoBundle 'will133/vim-dirdiff'
NeoBundle 'Valloric/YouCompleteMe', {
     \ 'build'      : {
        \ 'mac'     : './install.sh --clang-completer --system-libclang --omnisharp-completer',
        \ 'unix'    : './install.sh --clang-completer --system-libclang --omnisharp-completer',
        \ 'windows' : './install.sh --clang-completer --system-libclang --omnisharp-completer',
        \ 'cygwin'  : './install.sh --clang-completer --system-libclang --omnisharp-completer'
        \ }
     \ }
" Add or remove arguments to install.sh as necessary.
" Additional steps might be necessary for Windows, as always. ;)
let g:neobundle#install_process_timeout = 1500

NeoBundle 'Shougo/vimproc.vim', {
			\ 'build' : {
			\     'windows' : 'tools\\update-dll-mingw',
			\     'cygwin' : 'make -f make_cygwin.mak',
			\     'mac' : 'make -f make_mac.mak',
			\     'linux' : 'make',
			\     'unix' : 'gmake',
			\    },
			\ }
"NeoBundle 'Shougo/neocomplete.vim' <-- For this pluging I followed the github
"instructions and extracted(copy-passted) autoload,doc and plugin folder in
"~/.vim directory.



" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
"


" You can specify revision/branch/tag.
NeoBundle 'Shougo/vimshell', { 'rev' : '3787e5' }

" Required:
call neobundle#end()

" Required:
filetype plugin indent on

"---------------------------- End NeoBundle Scripts -------------------------

"*********************** NeoBundleFinish ****************************
"
"
"
"
"=====[ Show help files in a new tab, plus add a shortcut for helpg]==============

let g:help_in_tabs = 1

nmap <silent> H  :let g:help_in_tabs = !g:help_in_tabs<CR>

"Only apply to .txt files...
augroup HelpInTabs
    autocmd!
        autocmd BufEnter  *.txt   call HelpInNewTab()
        augroup END

"Only apply to help files...
        function! HelpInNewTab ()
            if &buftype == 'help' && g:help_in_tabs
                    "Convert the help window to a tab...
                            execute "normal \<C-W>T"
                                endif
                                endfunction
"
"
"
"Settings for syntastic plugin from its README file
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
"let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 1
"

"Go to Normal mode quickly
imap jk <Esc>



"
"Set the Leader key as space
let mapleader = "\<Space>"
"Open Vimrc in new file. Use :edit for opening it in current tab.
nmap <leader>v :tabedit $MYVIMRC<CR>

"NERDTree Settings
nmap <leader>nt :NERDTreeToggle<CR>

"Set autoindent
set autoindent
"Set line numbers and relative line numbers -  at this point I think they are
"awesome
set number
set relativenumber

"syntax on
syntax on


"set the syntax on
syntax enable

"highlighting the searches
set hlsearch " CTRL-L / CTRL-R W
set incsearch"

" Turn on the mouse, since it doesn't play well with tmux anyway. This way I can
" scroll in the terminal
set mouse=a


" Set to auto read when a file is changed from the outside
set autoread

" Display unprintable chars
set list
set listchars=tab:▸\ ,extends:❯,precedes:❮,nbsp:␣
set showbreak=↪

" How many lines to scroll at a time, make scrolling appears faster
set scrolljump=3

" Case insensitive search
set ignorecase
set smartcase

" Don't show matching brackets
set noshowmatch

" Tab settings
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set smarttab



" Text display settings
set linebreak
set textwidth=80
set autoindent
set nowrap
set whichwrap+=h,l,<,>,[,]


"from https://github.com/Valloric/dotfiles/blob/master/vim/vimrc.vim
" with this, we can now type ",." to exit out of insert mode
" if we really wanted to type ",.", then just type one char, wait half a sec,
" type another
inoremap ,. <Esc>
vnoremap ,. <Esc>



"from https://github.com/Valloric/dotfiles/blob/master/vim/vimrc.vim
"let g:airline_powerline_fonts = 1

"from https://github.com/Valloric/dotfiles/blob/master/vim/vimrc.vim
" key bindings for quickly moving between windows
" h left, l right, k up, j down
noremap <leader>h <c-w>h
noremap <leader>l <c-w>l
noremap <leader>k <c-w>k
noremap <leader>j <c-w>j









"Type <Space>w to save file (a lot faster than :w<Enter>):
noremap <Leader>w :w<CR>

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

```

and here is the snippet I tried for markdown files.
```
snippet fm
---
title: $1
date: $2
tags: $3
---
$0
endsnippet
```

**Comment by collegeimprovements** [comment] 2015-06-09 13:30
I removed `neosnippets`  from my vimrc file but the problem still persists.

**Comment by SirVer** [comment] 2015-06-11 06:04
Can you check `:verbose imap <tab>`?

**Comment by whatsthebeef** [comment] 2015-06-11 10:46
Same problem using Vim 7.4 in Mac

When I run `:verbose imap <tab> I see

i  <Tab>       * pumvisible() ? "\<C-N>" : "\<Tab>"
        Last set from ~/.vim/bundle/YouCompleteMe/autoload/youcompleteme.vim

But I have this setting in my vimrc

    let g:UltiSnipsExpandTrigger="<tab>"

The plugin doesn't work when YouCompleteMe isn't installed either.

Any ideas?

**Comment by whatsthebeef** [comment] 2015-06-11 11:24
After further investigation I have found

- The plugin picks up snippets from inside `all.snippets` but no others. So I have javascript.snippets inside the `~/.vim/bundle/vim-snippets/Ultisnips` directory but when I open app.js (with filetype `javascript`) it doesn't find the javascript snippets.
- When I select a snippet from all.snippets after a trigger (for example lorem) it doesn't expand the snippet.
- If I type `UltiSnipsEdit` it opens up an empty file at `~/.vim/Ultisnips/all.snippets`.
- When I move the `UltiSnips` directory from `~/.vim/bundles/vim-snippets` to `~/.vim` it still only picks up snippets from `all.snippets`.
- If I type `UltiSnipsEdit` after the move it opens up the `~/.vim/Ultisnips/all.snippets` and this time there is content because there is an existing file there.
- If I add "let g:UltiSnipsSnippetDirectories="/Users/john/.vim/bundle/vim-snippets/UltiSnips" it doesn't change anything.
- If I add "let g:UltiSnipsSnippetDirectories="UltiSnips"  it doesn't change anything.

I'm guessing this is unrelated to the issue @collegeimprovements has so I will open up a new issue.

**Comment by whatsthebeef** [comment] 2015-06-11 12:01
I removed the YouCompleteMe plugin after seeing 

   " Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.

Now there is no autocomplete at all again.

When I run `verbose imap <tab>` I see

    i  <Tab>       * <C-R>=UltiSnips#ExpandSnippet()<CR>
        Last set from ~/.vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim

**Comment by whatsthebeef** [comment] 2015-06-11 12:39
Okay, finally discovered that it doesn't seem to be setting the filetype.

When I set `UltiSnipsAddFiletypes` manually it finds the snippets.

At present I just have a few autocmds in my vimrc

    au FileType javascript :UltiSnipsAddFiletypes javascript

**Comment by collegeimprovements** [comment] 2015-06-11 18:28
followed the same guidelines as @whatsthebeef  has followed.
Still I don't get any snippet-completion :(

**Comment by mmwtsn** [comment] 2015-06-13 17:20
I had trouble getting everything to work as expected with `<tab>` as well. Following the advice from [this StackOverflow answer](http://stackoverflow.com/a/22253548) did the trick for me:

```vim
" if you use Vundle, load plugins:
Bundle 'ervandew/supertab'
Bundle 'Valloric/YouCompleteMe'
Bundle 'SirVer/ultisnips'

" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
```

**Comment by SirVer** [comment] 2015-06-15 06:22
You are missing 

` filetype plugin indent on`

and therefore your `ftdetect/UltiSnips.vim` file is not sourced. See https://github.com/Shougo/neobundle.vim again, the line is marked 'required' directly after neobundle end.

Closing, as I think that fixes the issue. Will reopen if that is not the case.

**Comment by absalonvaldes** [comment] 2015-08-02 08:01
Is there any way to add all filetypes availables automatically whitout autocmds?

**Comment by SirVer** [comment] 2015-08-02 08:21
This usually indicates that your vundle/plugin manager setup is faulty. Please post your entire vimrc.

**Comment by absalonvaldes** [comment] 2015-08-02 10:05
You are right. I was missing ```filetype off``` before Vundle setup. Sorry for that. Thanks.

**Comment by Behinder** [comment] 2015-09-17 22:46
I stopped using vim because in YCM i can use TAB to cycle on completions but there is no way to expand snippet by tab or even by "Enter". So I switched to Sublime 3 - its engine is IMO superior to VIM.

**Comment by vito-c** [comment] 2015-12-10 08:11
https://github.com/Valloric/YouCompleteMe/issues/420#issuecomment-55940039

**Comment by ohjames** [comment] 2015-12-10 20:51
@Behinder you stopped using vim due to a minor configuration issue then adopted a less configurable editor in reaction? Baffled.....

**Comment by Behinder** [comment] 2015-12-11 13:49
@ohjames i wouldn't call this MINOR issue if it's frustrating. And Sublime is not at all less configurable, period.

**Comment by ohjames** [comment] 2015-12-11 14:02
I moved out of my house because the blinds in the loft were too dark for my liking. So instead I moved into a house with no windows - its darkness is, IMO, superior to having to look at dark shabby blinds.

**Comment by SirVer** [comment] 2015-12-11 17:01
this bug tracker is not the place for these sorts of discussions. Please cease the off topic banter.

**Comment by nad2000** [comment] 2015-12-14 13:53
@SirVer, what is the solution of this issues. I'm having the same problem. I can cycle through snippets with <tab>, but I can't figure out how to expand them :( Tia, Rad

**Comment by vito-c** [comment] 2015-12-14 13:57
@nad2000 check out the comment I linked to this thread.

**Comment by phcerdan** [comment] 2016-01-07 22:54
Umm, is it possible that this configuration has stopped working? I was using it Ultisnips+SuperTab+YCM, and it was great, but I updated YCM and now tab is ciclying forward instead of triggering the snippet ...

**Comment by jakerobers** [comment] 2016-01-18 19:47
I am also having this issue. lorem<tab> works, but any snippets from other files do not.

**Comment by jakerobers** [comment] 2016-01-18 20:32
Fixed my issue:
I was trying to use angular snippets. They need to be manually loaded:

1. make a directory in .vim called `ftplugin`
2. create a file called javascript.vim
3. Put `:UltiSnipsAddFiletypes javascript-angular` in the file.

**Comment by tomspeak** [comment] 2016-02-20 01:51
Incase anyone is as silly as me, I went through everything everyone suggested:

```
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
```

`filetype plugin indent on`

And so forth, angered that after `:source ~/.vimrc` nothing was fixed, I had to reload MacVim and now it works flawlessly.

**Comment by elchinot7** [comment] 2016-03-18 06:16
I guys,

I had the same issue,  in my case the problem was a conflict between `Ultisnips` and `Rykka/riv.vim` plugins.  After removing `riv.vim` the `Tab` completion works as expected with

    let g:UltiSnipsExpandTrigger="<tab>"

After this change, the position of the line 

    filetype plugin indent on

respect to the `let g:Ultisnips*` lines makes no difference.

**Comment by himito** [comment] 2016-04-03 15:54
@elchinot7 You can use both `Ultisnips` and `Rykka/riv.vim`. You only need to set 
`let g:riv_ignored_imaps = "<Tab>,<S-Tab>" `in order to use `Tab` as expected.

**Comment by wesmat** [comment] 2016-04-23 16:45
I have the same tab expand problem.  I am running MacVim 7.4.2 and using the vim-plug manager.  Here .vimrc:

```
call plug#begin('~/.vim/plugged')
Plug 'SirVer/ultisnips'
call plug#end()

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
let g:UltiSnipsEditSplit="vertical"
```

I can run UltiSnipsEdit and this is my html.snippets file:

```
snippet t "test div" 
<div>
  test
</div>
endsnippet
```
When I edit an html file, it is syntax color coded, so I think the filetype is recognized.  How do I find what is wrong?

**Comment by seletskiy** [comment] 2016-04-24 11:57
@wesmat: Where do you store your html.snippets file?

**Comment by wesmat** [comment] 2016-04-24 12:03
I am using the default location.  When I edit it says:

`"~/UltiSnips/html.snippets"`

**Comment by wesmat** [comment] 2016-04-30 04:18
I am fairly sure that vim-plug did not properly install ultisnips.  How do I check it or should I remove and do a manual install - which means I need manual install instructions.

**Comment by rafaelrinaldi** [comment] 2016-05-25 20:49
I'm also having the same problem. UltiSnips suddenly stopped expanding snippets.

Running `:verbose imap <tab>` (suggested by @SirVer) gives me the following output:

```
i  <Tab>       * <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>
        Last set from ~/.vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
```

I've enabled all the config options suggested by @whatsthebeef:

```viml
let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<tab>'
let g:UltiSnipsJumpBackwardTrigger='<s-tab>'
let g:UltiSnipsEditSplit='vertical'
```

I use Vundle as my plugin manager.

Any ideas?

**Comment by seletskiy** [comment] 2016-05-26 04:18
@rafaelrinaldi: Unfortunately, neovim is not supported by me, because it's too unstable.

**Comment by rafaelrinaldi** [comment] 2016-05-26 14:59
@seletskiy After keeping up with the project for a while I'll have to agree with you. I just switched back to Vim (the latest build) and everything is working perfectly.

Thanks.

**Comment by justinmk** [comment] 2016-06-05 03:45
> UltiSnips suddenly stopped expanding snippets

@rafaelrinaldi It was working in an earlier Neovim version? If so, can you give a rough idea of which? Were you compiling from HEAD or using a packaged version (0.1.2, 0.1.3, ...)

**Comment by rafaelrinaldi** [comment] 2016-06-05 03:56
@justinmk Yeah, I never had the issue before. I first noticed it after upgrading neovim through homebrew (not HEAD, the regular release).

**Comment by justinmk** [comment] 2016-06-05 03:58
@rafaelrinaldi Did you also update the neovim python module? 

    pip  install --upgrade neovim

(or pip2/pip3 depending on your distro, etc...)

**Comment by rafaelrinaldi** [comment] 2016-06-05 04:00
@justinmk Yes, I did. I usually do this after I upgrade Neovim (people always recommend doing this before submitting an issue, etc).

**Comment by duganchen** [comment] 2016-06-05 04:01
While I cannot speak for rafaelrlnaldi, I just did a test with neovim 0.14 and init.vim that contains *only* the following:

    syntax on
    call plug#begin('~/.config/nvim/plugged')
    Plug 'SirVer/ultisnips'
    call plug#end()

And that did actually work for me.

**Comment by duganchen** [comment] 2016-06-05 04:55
@rafaelrinaldi Can you please try the following? Update your plugin manager to the latest version (I use vim-plug), clear out your entire plugins/bundle directory, reinstall all the plugins (with vim-plug that would be :PlugInstall), and rebuild YouCompleteMe if you use it.

UltiSnips started working for me again after I did that. Please let me know if it starts working for you after you do that.

**Comment by rafaelrinaldi** [comment] 2016-06-06 15:04
@duganchen Thanks for helping out. I did a fresh install and now it seems to be working fine!

**Comment by haifengkao** [comment] 2016-08-06 03:10
confirmed. It works on fresh install

**Comment by haifengkao** [comment] 2016-08-06 18:00
executing `:verbose imap <tab>` in neovim
I got:

```
i  <Tab>         <Plug>SuperTabForward
	Last set from ~/.config/nvim/plugged/supertab/plugin/supertab.vim
```
In vim I got:
```
i  <Tab>       * <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>
	Last set from ~/.vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
```
The plugin loading orders are different

**Closed** 2016-09-05 14:12 UTC

**Comment by z-jason** [comment] 2016-11-05 17:53
For someone who cannot get UltiSnips working and stumble upon this issue, here are what I did to finally get it working (I didn't install **YouCompleteMe**)

Initially, I set the two **UltiSnips** options as these
```
let g:UltiSnipsSnippetsDir='/Users/[user_name]/.vim/mysnippets'
let g:UltiSnipsSnippetDirectories='/Users/[user_name]/.vim/mysnippets'
```

Later I found this in **UltiSnips** help page (`:h UltiSnips-snippet-search-path`)

> UltiSnips will search each 'runtimepath' directory for the subdirectory names
defined in g:UltiSnipsSnippetDirectories in the order they are defined.

And the example the help page provides is 
```
let g:UltiSnipsSnippetDirectories=["UltiSnips"]
```
Thus, I change my configuration to these and it works!
```
let g:UltiSnipsSnippetsDir='/Users/[user_name]/.vim/mysnippets'
let g:UltiSnipsSnippetDirectories=["mysnippets"]
```

**Comment by herrbischoff** [comment] 2017-02-20 12:40
Although this is closed, I ran into the same issue. What fixed it for me was adding:

```vim
" Add home directory to runtimepath
set rtp^=$HOME
```

to the bottom of my `.vimrc` (or rather `init.vim`). This made UltiSnips work with a (default?) `~/UltiSnips` directory.

**Comment by math2001** [comment] 2017-09-09 06:20
It's still not working for me, at all.

My snippets are in `~/dotfiles/vim-snippets/`. I reset my `.vimrc` to this, but it still doesn't work.
```
syntax on
filetype plugin indent on

call plug#begin('~/.vim/plugged')

Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

call plug#end()

let UltiSnipsExpandTrigger = "<tab>"
let UltiSnipsListSnippets = "<c-tab>"
let UltiSnipsJumpForwardTrigger = "<c-j>"
let UltiSnipsJumpBackwardTrigger = "<c-k>"

let UltiSnipsEditSplit = "vertical"
let UltiSnipsUsePythonVersion = 3
let UltiSnipsSnippetsDir = "~/dotfiles/vim-snippets/"
let UltiSnipsSnippetsDirectories = ["vim-snippets"]
let UltiSnipsEnabledSnipMate = 0
```
As you can see, I use `vim-plug`.

Runtime path:

```
runtimepath=~/.vim,~/.vim/plugged/ultisnips/,~/.vim/plugged/vim-snippets/,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,~/.vim/plugged/ultisnips/after,~/.vim/after
```

I'm on Windows 10 bash. I also tested with cygwin (mintty) previously, it wasn't working either.

**Comment by sebpearce** [comment] 2017-12-01 05:25
I solved this by changing
```
let g:UltiSnipsSnippetsDir="~/config-files/ultisnips/"
let g:UltiSnipsSnippetDirectories=["ultisnips"]
```
to
```
let g:UltiSnipsSnippetsDir="~/.vim/ultisnips"
let g:UltiSnipsSnippetDirectories=["ultisnips"]
```
and moving my snippets into `~/.vim/ultisnips`.

**I suspected that the issue was that `~/config-files/ultisnips` wasn't in my runtimepath, and it looks like that was correct.**

You don't have to move your snippets into the `.vim` dir by the way. I'm still keeping my `~/config-files/ultisnips` by creating a symlink to it from `~/.vim/ultisnips`:

`ln -s ~/config-files/ultisnips ~/.vim/ultisnips`

**Comment by i-give-up** [comment] 2018-03-04 03:07
Environment
- gVim 8.0
- Windows 8.1
- UltiSnips commit 423f264e753cec260b4f14455126e6db7ba429af

The issue is that tab trigger works fine when I use default snippets from "honza/vim-snippets" e.g. `date`, `lorem`. But if I use `:UltiSnipsEdit` to create a private snippet, then tab trigger doesn't work for the private snippet.

## Cause

By default, the variable `g:UltiSnipsSnippetsDir` (i.e. directory in which private snippets are saved) is not set. The default behavior when that variable is not set seems to be to save private snippets in `UltiSnips` (maybe depends on your `g:UltiSnipsSnippetDirectories` value?) directory in the current working directory. This is *bad* because UltiSnips looks for snippets in runtimepath directories (see `:h UltiSnips-snippet-search-path`) and chances are your private snippets would not be saved in those directories with the default settings.

## Solution

Set `g:UltiSnipsSnippetsDir` to somewhere in the runtimepath in your vimrc. In my case 

    let g:UltiSnipsSnippetsDir = "~/vimfiles/UltiSnips"

Replace `vimfiles` with `.vim` if using Linux.

I feel like this should be mentioned in the Quickstart section of README.md

**Comment by pak11273** [comment] 2018-11-01 17:16
If you are using YCM and are trying to create a snippet on the fly but hit tab and nothing happens, then this may be for you.  Add this to your .vimrc:

`autocmd FileType snippets :UltiSnipsAddFiletypes snippets`

**Comment by LarryMckuydee** [comment] 2019-07-04 04:14
> For someone who cannot get UltiSnips working and stumble upon this issue, here are what I did to finally get it working (I didn't install **YouCompleteMe**)
> 
> Initially, I set the two **UltiSnips** options as these
> 
> ```
> let g:UltiSnipsSnippetsDir='/Users/[user_name]/.vim/mysnippets'
> let g:UltiSnipsSnippetDirectories='/Users/[user_name]/.vim/mysnippets'
> ```
> 
> Later I found this in **UltiSnips** help page (`:h UltiSnips-snippet-search-path`)
> 
> > UltiSnips will search each 'runtimepath' directory for the subdirectory names
> > defined in g:UltiSnipsSnippetDirectories in the order they are defined.
> 
> And the example the help page provides is
> 
> ```
> let g:UltiSnipsSnippetDirectories=["UltiSnips"]
> ```
> 
> Thus, I change my configuration to these and it works!
> 
> ```
> let g:UltiSnipsSnippetsDir='/Users/[user_name]/.vim/mysnippets'
> let g:UltiSnipsSnippetDirectories=["mysnippets"]
> ```

Stuck for 3 hours you just save my life

**Comment by PaddiM8** [comment] 2019-07-06 17:52
I'm using Neovim, and struggled with this problem for a few hours. Finally, I decided to check that my ~/.vim directory *actually* is in the runtime path. **It was not**. After moving my snippet folder to ~/.config/nvim instead, it started to work!

**Comment by dhilst** [comment] 2021-04-29 20:35
In my case it was not working because I need an `w` modifier in the snippet

```
snippet nulll "" w
new NullLogger<$1>()
```

Without this it will not expand in some situations

**Comment by asanchez75** [comment] 2022-05-25 09:49
In my case it was not working because I had this line
```
" disable automatic paste indentation
set paste
```
I removed it and it works!
