### ISSUE TITLE
python warning at startup

### ISSUE THREAD

**Issue by nilsbecker** [SirVer/ultisnips#1199] opened 2020-03-24 09:51 UTC
**Expected behavior:**

no warnings in vim on normal startup

**Actual behavior:**

i get an error message echoed in vim reproducibly when first opening a file. in this case with filetype tex but i don't think it's related. the error/warning appears only once.

**Steps to reproduce**

macvim, macos 10.12. open a file and invoke a snippet. 

-----

- **Operating System**: 
macos 10.12
- **Vim Version**: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  3 2020 12:05:00)
macOS version
Included patches: 1-319

- **UltiSnips Version**: 
git rev-parse origin/master
ee31ea1c7d08ced8577120b4c1d55c5a05351a75

- **Python inside Vim**: 

python3 3.7.7
<img width="838" alt="Screen Shot 2020-03-24 at 10 42 50" src="https://user-images.githubusercontent.com/177614/77411870-617c3d00-6dbd-11ea-840e-6c62114d1d8c.png">

**Comment by SirVer** [comment] 2020-03-30 13:22
This is a confusing error.... The problem seems to be this ```Support for nested sets and set operations in regular expressions as in Unicode Technical Standard #18 might be added in the future. This would change the syntax. To facilitate this future change a FutureWarning will be raised in ambiguous cases for the time being. That include sets starting with a literal '[' or containing literal character sequences '--', '&&', '~~', and '||'. To avoid a warning, escape them with a backslash. (Contributed by Serhiy Storchaka in bpo-30349.)```, from this page: https://docs.python.org/dev/whatsnew/3.7.html

The code this points to is using the trigger, which in this case is a regular expression which has unescaped set operations. So the problem is not with UltiSnips, but with some trigger in the files that are loaded for the file you are editing. 

Closing as this is unfortunately not very actionable for the engine.

**Closed by SirVer** 2020-03-30 13:22 UTC

**Comment by nilsbecker** [comment] 2020-03-30 14:47
i see. can i find out what snippet file this warning comes from? the line number seemed to indicate a file from the ultisnips distribution, so that gives no hint.

**Comment by SirVer** [comment] 2020-03-31 05:58
Unfortunately there is no easy way - you have to comment out all regular expression snippets of all files mentioned in `:UltiSnipsEdit!` and see which one makes the problem.
