### ISSUE TITLE
Cannot add text to consecutive tabstops

### ISSUE THREAD

**Issue by kawing-chiu** [SirVer/ultisnips#457] opened 2015-03-06 09:05 UTC
Consider the following snippet:
```
snippet t "generic html tag" w
<$1`!p
snip.rv += ""
if t[2]:
  snip.rv += ' '
`$2>$3</$1>
endsnippet
```
When I type
```
t<Tab>img<C-j>src=
```
I am expecting to get
```
<img src=></img>
```
However, i get this:
```
<imgsrc=></imgsrc=>
```
That is, when `$2` is put "immediately" (in fact not, because content is added dynamically between `$1` and `$2`) after `$1`, I have no way to add text to `$2`. I consider this a bug because no matter how I arrange the tabstops I should be able to jump to and add text to it.

**Comment by SirVer** [comment] 2015-03-08 18:19
dupe of https://github.com/SirVer/ultisnips/issues/158

**Closed by SirVer** 2015-03-08 18:19 UTC

**Comment by kawing-chiu** [comment] 2015-03-11 02:22
Hi. Sorry for reporting a duplicate issue. After reading #158, it is not clear to me what the current status of this issue is. Will this be fixed in the foreseeable future?

**Comment by SirVer** [comment] 2015-03-12 04:08
An open bug means the problem is acknowledged and ready to be worked on. The constant problem is that there are more open bugs than active contributors (hint, hint). 

I have currently only enough time available to keep UltiSnips maintained - so I cannot commit on fixing it soon. If you are annoyed by it and want to fix it, I will provide guidance on how to go about it.

**Comment by kawing-chiu** [comment] 2015-03-13 07:37
Well, I have attempted to do something about it:
```
diff --git a/pythonx/UltiSnips/snippet_manager.py b/pythonx/UltiSnips/snippet_manager.py
index c12a529..06810d1 100644
--- a/pythonx/UltiSnips/snippet_manager.py
+++ b/pythonx/UltiSnips/snippet_manager.py
@@ -319,7 +319,7 @@ class SnippetManager(object):
                     lt = '\n'.join(lt)
                     ct = '\n'.join(ct)
                     es = diff(lt, ct, initial_line)
-                self._csnippets[0].replay_user_edits(es)
+                self._csnippets[0].replay_user_edits(es, self._ctab)
             except IndexError:
                 # Rather do nothing than throwing an error. It will be correct
                 # most of the time
diff --git a/pythonx/UltiSnips/text_objects/_base.py b/pythonx/UltiSnips/text_objects/_base.py
index 24e9a21..6855b48 100644
--- a/pythonx/UltiSnips/text_objects/_base.py
+++ b/pythonx/UltiSnips/text_objects/_base.py
@@ -183,7 +183,7 @@ class EditableTextObject(TextObject):
     ###############################
     # Private/Protected functions #
     ###############################
-    def _do_edit(self, cmd):
+    def _do_edit(self, cmd, ctab=None):
         """Apply the edit 'cmd' to this object."""
         ctype, line, col, text = cmd
         assert ('\n' not in text) or (text == '\n')
@@ -201,7 +201,12 @@ class EditableTextObject(TextObject):
                     break
                 elif ((child._start <= pos <= child._end) and
                         isinstance(child, EditableTextObject)):
-                    child._do_edit(cmd)
+                    try:
+                        if ctab.number != child.number:
+                            continue
+                    except AttributeError:
+                        pass
+                    child._do_edit(cmd, ctab)
                     return
             else:  # Deletion
                 delend = pos + Position(0, len(text)) if text != '\n' \
@@ -214,7 +219,7 @@ class EditableTextObject(TextObject):
                         new_cmds.append(cmd)
                         break
                     else:
-                        child._do_edit(cmd)
+                        child._do_edit(cmd, ctab)
                         return
                 elif ((pos < child._start and child._end <= delend) or
                         (pos <= child._start and child._end < delend)):
diff --git a/pythonx/UltiSnips/text_objects/_snippet_instance.py b/pythonx/UltiSnips/text_objects/_snippet_instance.py
index f70d7ed..d5dfc64 100644
--- a/pythonx/UltiSnips/text_objects/_snippet_instance.py
+++ b/pythonx/UltiSnips/text_objects/_snippet_instance.py
@@ -45,11 +45,11 @@ class SnippetInstance(EditableTextObject):
                     _place_initial_text(child)
         _place_initial_text(self)
 
-    def replay_user_edits(self, cmds):
+    def replay_user_edits(self, cmds, ctab=None):
         """Replay the edits the user has done to keep endings of our Text
         objects in sync with reality."""
         for cmd in cmds:
-            self._do_edit(cmd)
+            self._do_edit(cmd, ctab)
 
     def update_textobjects(self):
         """Update the text objects that should change automagically after the
```
Something like the above fixes my issue, but causes some 20 tests to fail. I don't fully understand those recursive functions yet and indeed need some help to go further.

**Comment by kawing-chiu** [comment] 2015-03-13 12:10
Adding one more line reduces failed tests to 3:
```
@@ -201,7 +201,18 @@ class EditableTextObject(TextObject):
                     break
                 elif ((child._start <= pos <= child._end) and
                         isinstance(child, EditableTextObject)):
-                    child._do_edit(cmd)
+                    if pos == child.end:
+                        try:
+                            if ctab.number != child.number:
+                                continue
+                        except AttributeError:
+                            pass
+                    child._do_edit(cmd, ctab)
                     return
             else:  # Deletion
                 delend = pos + Position(0, len(text)) if text != '\n' \
```

**Comment by kawing-chiu** [comment] 2015-03-13 13:36
Augmenting the `if` condition a bit seems to solve the problem:
```
if pos == child.end and not child.children:
```
Now all tests can be passed.
