### ISSUE TITLE
Can't jump to another tabstop after completion confirm

### ISSUE THREAD

**Issue by Posto578** [SirVer/ultisnips#927] opened 2018-01-26 15:17 UTC
When I use completion inside a snippet it disable all snip and can't go to next placeholder.

![impeccablefabulousizuthrush-size_restricted](https://user-images.githubusercontent.com/35492119/35446220-52eda02e-02b4-11e8-970e-563544dfb13b.gif)

`vimrc`
```
set nu
filetype plugin on
inoremap jj <esc>
map <space> /
map <c-space> ?
vnoremap . :norm.<CR>
noremap <C-s> :update<CR>
set incsearch
set nohlsearch

abbr consider //consider the following statement

call plug#begin()
Plug 'jacoborus/tender.vim'
Plug 'kien/ctrlp.vim'
Plug 'vim-scripts/taglist.vim'
Plug 'junegunn/vim-easy-align'
Plug 'honza/vim-snippets'
Plug 'Rip-Rip/clang_complete'
Plug 'SirVer/ultisnips'
call plug#end()

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

"clnag_complete settings
let g:clang_jumpto_declaration_key=''
let g:clang_library_path='/Applications/Xcode.app/Contents/Developer/Toolchains/
let g:clang_snippets_engine = 'ultisnips'
let g:clang_user_options = '-std=c++11'
let g:clang_snippets = 1
let g:clang_close_preview = 1

nmap <F8> :TagbarToggle<CR>

if (has("termguicolors"))
 set termguicolors
endif

" Theme
syntax enable
colorscheme tender

let macvim_skip_colorscheme=1
```

**Comment by andreyorst** [comment] 2018-04-10 15:38
Seems related to #822. I can't be sure but in the gif you provided there is some window that pops up at the bottom after you confirm completion. It basically disables snippet placeholders.

**Comment by SirVer** [comment] 2019-12-09 16:46
I wash unable to reproduce the problem - with the given vimrc I do not get automatic completion, so maybe some configuration is missing? 

However I agree with @andreyorst that this is likely related to #822 and should therefore be mixed. Therefore closing as likely fixed and definitely not reproducible.

**Closed by SirVer** 2019-12-09 16:46 UTC
Labels: questionable
