### ISSUE TITLE
Updated this and getting ImportError: No module named site

### ISSUE THREAD

**Issue by cmosguy** [SirVer/ultisnips#693] opened 2016-04-28 22:14 UTC
@SirVer I just updated this plugin in my vim bundle and it crashes my vim.

I keep getting this error:

ImportError: No module named site

Please advise!
Thanks!

**Comment by SirVer** [comment] 2016-04-29 12:50
This is very little information you are posting. Please add Vim version, OS, python version.

The bug you are seeing is likely unrelated to UltiSnips and a symptom of a broken Vim and/or Python installation:

http://stackoverflow.com/questions/19089654/vim-shows-importerror-no-module-named-site-while-i-am-using-canopy1-1
https://github.com/davidhalter/jedi-vim/issues/207
https://github.com/Homebrew/legacy-homebrew/issues/26496
http://vim.1045645.n5.nabble.com/MacVim-Snapshot-71-td5717255.html

Closing, please reopen if you know that this is caused by UltiSnips and not by Python in Vim.

**Closed by SirVer** 2016-04-29 12:50 UTC
