### ISSUE TITLE
Can't create new snippets

### ISSUE THREAD

**Issue by rfloc** [SirVer/ultisnips#871] opened 2017-07-15 15:20 UTC
I can't create new snippets. The snippets that already come with the plugin are working perfectly, however the snippets I create don't work. This is shown in the image below.
![snip](https://user-images.githubusercontent.com/24982999/28240355-d5cfc172-6956-11e7-81e1-f563c377c235.jpg)

I installed the plugin using Vundle. Then I put the following commands in my .vimrc file
`let g:UltiSnipsExpandTrigger="<C-l>"`
`let g:UltiSnipsJumpForwardTrigger="<c-k>"`
`let g:UltiSnipsJumpBackwardTrigger="<c-j>"`
`let g:UltiSnipsEditSplit="vertical"`
`let g:UltiSnipsSnippetDirectories = ['~/.vim/my-snippets/UltiSnips', 'UltiSnips']`
`set runtimepath+=~/.vim/ultisnips_rep`

Then I typed the commands below into the terminal:
`mkdir -p ~/.vim/ftdetect/`
`ln -s ~/.vim/ultisnips_rep/ftdetect/* ~/.vim/ftdetect/`

**Comment by andreyorst** [comment] 2018-04-06 10:04
Please see https://github.com/SirVer/ultisnips/issues/956#issuecomment-377816395

Closing because it is duplicate of #948

**Closed by andreyorst** 2018-04-06 10:04 UTC
