### ISSUE TITLE
After you completed items, neosnippet creates snippet item automatically

### ISSUE THREAD

**Issue by 7belrhalmia** [SirVer/ultisnips#556] opened 2015-08-23 11:47 UTC
when you complete something with neocomplete , ultisnips create automaticly a snippet for you so when you press tab it insert all function prototype for you it's already done in neosnippet

i wish you to add this feature

**Comment by SirVer** [comment] 2015-08-24 05:12
I *think* this is a duplicate of #555 . Closing, please speak up if you disagree.

**Closed by SirVer** 2015-08-24 05:12 UTC
