### ISSUE TITLE
Issues with circulating between placeholders 

### ISSUE THREAD

**Issue by Trid-collab** [SirVer/ultisnips#1395] opened 2021-09-24 10:17 UTC
I am using Neovim stable with nvim.cmp and cmp-nvim-ultisnips
But  noticed that the I am not able to circulate the snippet placeholders using tabs like it was working before. Its not even working in the neovim stable release. When I am typing in the snippet placeholder the autocompletes are popping up while I am typing. On completion I am not able to use the tabs to move to the next placeholder.

This working earlier before -few days back
This is my mapping setup. I am sorry I am no expert on this. Just tried to follow some leads which I picked up while going through the configs of others and it worked for me till recently

	mapping = {
		["<C-p>"] = cmp.mapping.select_prev_item(),
		["<C-k>"] = cmp.mapping.select_prev_item(),
		["<C-n>"] = cmp.mapping.select_next_item(),
		["<C-j>"] = cmp.mapping.select_next_item(),
		["<C-d>"] = cmp.mapping.scroll_docs(-4),
		["<C-f>"] = cmp.mapping.scroll_docs(4),
		["<C-e>"] = cmp.mapping.close(),
		["<CR>"] = cmp.mapping.confirm({
			behavior = cmp.ConfirmBehavior.Insert,
			select = true,
		}),
		["<C-Space>"] = cmp.mapping(function(fallback)
			if vim.fn.pumvisible() == 1 then
				if vim.fn["UltiSnips#CanExpandSnippet"]() == 1 then
					return vim.fn.feedkeys(t("<C-R>=UltiSnips#ExpandSnippet()<CR>"))
				end
				vim.fn.feedkeys(t("<C-n>"), "n")
			elseif check_back_space() then
				vim.fn.feedkeys(t("<cr>"), "n")
			else
				fallback()
			end
		end, {
			"i",
			"s",
		}),
		["<Tab>"] = cmp.mapping(function(fallback)
			if vim.fn.complete_info()["selected"] == -1 and vim.fn["UltiSnips#CanExpandSnippet"]() == 1 then
				vim.fn.feedkeys(t("<C-R>=UltiSnips#ExpandSnippet()<CR>"))
			elseif vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
				vim.fn.feedkeys(t("<ESC>:call UltiSnips#JumpForwards()<CR>"))
			elseif vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(t("<C-n>"), "n")
			elseif check_back_space() then
				vim.fn.feedkeys(t("<tab>"), "n")
			else
				fallback()
			end
		end, {
			"i",
			"s",
		}),
		["<S-Tab>"] = cmp.mapping(function(fallback)
			if vim.fn["UltiSnips#CanJumpBackwards"]() == 1 then
				return vim.fn.feedkeys(t("<C-R>=UltiSnips#JumpBackwards()<CR>"))
			elseif vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(t("<C-p>"), "n")
			else
				fallback()
			end
		end, {
			"i",
			"s",
		}),
	},

My plugin setup

	use({
		"SirVer/ultisnips",
		requires = { "honza/vim-snippets" },
		config = function()
			vim.g.UltiSnipsRemoveSelectModeMappings = 0
		end,
	})

**Comment by xvzc** [comment] 2023-12-24 04:21
This is more like nvim-cmp related question. `vim.fn.pumvisible()` is no longer working. See `cmp.visible()` instead.

**Comment by SirVer** [comment] 2024-01-03 19:37
Sorry, if you cannot reproduce in Vanilla Vim there is very little chance this will be fixed.

This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).

**Closed by SirVer** 2024-01-03 19:37 UTC
