### ISSUE TITLE
nvim is stuck when expand snip and then move to other file

### ISSUE THREAD

**Issue by SolaWing** [SirVer/ultisnips#1189] opened 2020-03-07 09:47 UTC
**Expected behavior:**
ui shouldn't stuck

**Actual behavior:**
ui block serveral seconds

**Steps to reproduce**

1. given snippet:
```
snippet f "func def"
func ${1:name}($2)${3/ .*/ ->/}${3} {
	$0
}
endsnippet
```
2. nvim open two files, one is the file expand snip, other is any file with more than hundreds lines
3. expand func snip, `escape`, `gt` to next file.
4. ui block for several seconds

-----
 **Other test infomation**
cProfile infomation
```
      624    0.004    0.000    9.817    0.016 /usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/selectors.py:553(select)
      624    9.812    0.016    9.812    0.016 {method 'control' of 'select.kqueue' objects}
       27    0.000    0.000    9.020    0.334 /usr/local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py:193(handler)
       26    0.000    0.000    9.016    0.347 /usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py:206(filter_request_cb)
       25    0.000    0.000    9.015    0.361 /usr/local/lib/python3.7/site-packages/pynvim/plugin/script_host.py:88(python_execute)
       26    0.000    0.000    8.992    0.346 {built-in method builtins.exec}
        2    7.944    3.972    8.613    4.306 /Users/wang/.vim/bundle/ultisnips/pythonx/UltiSnips/diff.py:159(diff)
```

diff call env:
a is the snip expand line, b is the **all contents** of the file move to. stack is:
```
  File "/usr/local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 195, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 210, in filter_request_cb
    result = request_cb(name, args)
  File "/usr/local/lib/python3.7/site-packages/pynvim/plugin/host.py", line 104, in _on_request
    rv = handler(*args)
  File "/usr/local/lib/python3.7/site-packages/pynvim/plugin/host.py", line 82, in _wrap_function
    return fn(*args)
  File "/usr/local/lib/python3.7/site-packages/pynvim/plugin/script_host.py", line 93, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 1, in <module>
  File "/Users/wang/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/Users/wang/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 407, in _cursor_moved
    es = diff(lt, ct, initial_line)
  File "/Users/wang/.vim/bundle/ultisnips/pythonx/UltiSnips/diff.py", line 179, in diff
    traceback.print_stack(file=sys.stdout)
```

-----

- **Operating System**: Mac OS 10.15.3 
- **Vim Version**: NVIM v0.4.3
- **UltiSnips Version**: master e910b4f
- **Python inside Vim**: 3.7.6

**Comment by SirVer** [comment] 2020-03-09 13:44
Cannot repro on core Vim and also did a quick test with neovim and could not repro there either - however I am very unfamiliar with Neovim. This should definitely not happen on NeoVim neither, since moving to a different buffer should yield an autocommand that should terminate the current snippet. Did you somehow disable AutoCommands maybe? 

Closing, since NeoVim is not supported and since I cannot repro without full Vim config.




This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).

**Closed by SirVer** 2020-03-09 13:44 UTC

**Comment by SolaWing** [comment] 2020-03-20 07:54
@SirVer nvim autocmd's order when use gt, indeed is CursorMoved, and then BufEnter. I test with nvim -u NONE. 
when move between window, it's ok with enter then moved. I will report to nvim

**Comment by SolaWing** [comment] 2020-03-20 08:18
I add a `autocmd BufLeave * call UltiSnips#LeavingBuffer()` to solve this problem

**Comment by rwmpelstilzchen** [comment] 2023-06-05 23:34
Haven’t got the chance to test whether it does solve this, but https://github.com/neovim/neovim/pull/23711 should solve https://github.com/neovim/neovim/issues/12031, which causes the problem described here.
