### ISSUE TITLE
Neovim freezes when pressing unmapped f key (ex: f2,f3,f5) in insert mode

### ISSUE THREAD

**Issue by ilnc00** [SirVer/ultisnips#1225] opened 2020-05-12 22:46 UTC
**Expected behavior:**
In insert mode, pressing unmapped f keys,like F2,F3,F5... inserts <F2>,<F3>,<F5>

**Actual behavior:**
Neovim freezes in insert mode, <Esc> and <C-c> do not work, nor do any other keys (or keybindings I have tried). I have to close the terminal emulator.

** What I tried **
I tried uninstalling every plugin and then reinstalling only Ultisnips (via vim-plug), but the problem still persist.

The temporary fix I found is to imap the unmapped keys to anything or to <Nop>.

**Steps to reproduce**
To show the issue I went into my init.vim file. When Ultisnips is disabled, there is the expected behavior. After uncommenting the line and sourcing init.vim, entering f5 in insert mode froze nvim.
![nvimgif](https://user-images.githubusercontent.com/65257665/81752661-87e25e80-9477-11ea-88f8-fcbd97a80f6d.gif)

The .vimrc used is 
![init vim](https://user-images.githubusercontent.com/65257665/81751955-181fa400-9476-11ea-990e-ffd0d8df5e68.png)

1. Enter insert mode
2. Press an F2, F3, F5, or any unmapped F key 
3. It freezes
3. If the line "imap <F5> <Nop> is uncommented then pressing F5 in insert mode does nothing (as expected)

-----

- **Operating System**: Manjaro Linux (5.6.11-1), KDE Plasma (5.18.5)
- **Vim Version**:  NVIM v0.4.3, Build type: Release

- **UltiSnips Version**: e35158d 
- **Python inside Vim**: 3.8.2
- **Docker repo/vimrc**: N/A

**Comment by lacygoill** [comment] 2020-05-13 03:12
Duplicate of https://github.com/SirVer/ultisnips/issues/1202.
Update pynvim so that it includes [this commit](https://github.com/neovim/pynvim/commit/3791b2581eac4d2f1a829ab6792a122a0bb914fc).

**Comment by ilnc00** [comment] 2020-05-13 03:30
Thanks, that solved it.

**Closed** 2020-05-13 03:31 UTC
