### ISSUE TITLE
doesn't detect tex format

### ISSUE THREAD

**Issue by lx93uv** [SirVer/ultisnips#824] opened 2017-02-17 19:48 UTC
Snippets doesn't expanded with `tex` file format.

`vim 8`, `vim-plug`

I am trying to add custom snippets; here is my `.vimrc` excerpt (without extra snippets collection plugins):
```vim
set guioptions-=T                                                               
set guioptions -=m                                                              
                                                                                
set gfn=Ubuntu\ Mono\ 12                                                        
                                                                                
imap jj <Esc>                                                                   
set nocompatible                                                                
syntax on                                                                       
filetype plugin indent on                                                       
set background=light                                                            
set noswapfile                                                                  
set colorcolumn=80                                                              
set nowrap                                                                      
set autoindent                                                                  
set softtabstop=2                                                               
set tabstop=2                                                                   
set shiftwidth=2                                                                
set expandtab                                                                   
set backspace=indent,eol,start                                                  
                                                                                
call plug#begin('~/.vim/plugged')                                               
  Plug 'tpope/vim-commentary'                                                   
  Plug 'SirVer/ultisnips'                                                       
  Plug 'easymotion/vim-easymotion'                                              
  Plug 'ctrlpvim/ctrlp.vim'                                                     
call plug#end()                                                                 
                                                                                
let g:EasyMotion_do_mapping = 0 " Disable default mappings                      
nmap <Space><Space> <Plug>(easymotion-overwin-f2)                               
                                                                                
" Turn on case insensitive feature                                              
let g:EasyMotion_smartcase = 1                                                  
                                                                                
" JK motions: Line motions                                                      
map <Leader>j <Plug>(easymotion-j)                                              
map <Leader>k <Plug>(easymotion-k)                                              
                                                                                
let g:UltiSnipsSnippetDirectories=$HOME.'/.vim/snippets'                        

let g:UltiSnipsExpandTrigger="<tab>"                                            
let g:UltiSnipsJumpForwardTrigger="<c-b>"                                       
let g:UltiSnipsJumpBackwardTrigger="<c-z>" 
```

`ultisnips` starts works only after execution `UltiSnipsAddFiletypes tex`. With other file types it works ok.

I had also check this with `honzo` plugin.

**Comment by lx93uv** [comment] 2017-02-17 20:27
Command `:UltiSnipsEdit` opens `plaintext.snippet`.

**Comment by chrisrytting** [comment] 2017-02-21 17:13
@lx93uv The same thing happened for me until my tex file actually had a preamble, at which point `:UltiSnipsEdit` opened the appropriate `tex.snippet`

**Comment by lx93uv** [comment] 2017-02-23 16:18
@chrisrytting in my case it creates $PROJECT/UltiSnips/plaintext.snippets  (per project) file.

**Comment by andreyorst** [comment] 2018-04-10 10:27
> in my case it creates $PROJECT/UltiSnips/plaintext.snippets (per project) file.
that's because 
```vim
let g:UltiSnipsSnippetDirectories=$HOME.'/.vim/snippets'
```
is defined wrong. First of all `snippets` directory name is [reserved for snipMate snippets](https://github.com/SirVer/ultisnips/blob/36f5618745dcbcf7640b60625b266a9aaaf9e43a/doc/UltiSnips.txt#L207). Second, it should be [list](https://github.com/SirVer/ultisnips/blob/36f5618745dcbcf7640b60625b266a9aaaf9e43a/doc/UltiSnips.txt#L403):
```vim
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']

```

**Comment by andreyorst** [comment] 2018-04-11 12:31
> Command :UltiSnipsEdit opens plaintext.snippet.

Correct me if Im wrong, but it opens `plaintex.snippets`, not `plaintext.snippets`. Plain**tex** is selected when file is empty on open, but contains `.tex` extension. However if tex file is containing preamble, vim deduces it as `tex` filetype.

The same occurs if you will open file `script.txt` in vim. It will be opened as `text` filetype. But if you add `#!/bin/bash` to the begining of this file, and reopen it, vim will detect header, and switch to `sh` filetype, despite the fact that file has `.txt` extension. That's useful because most of files in linux are not containing extensions, and because vim need to know what type of file it opens, to use filetype indent and other ft features, it deduces fyletype from file contents. 

I'm closing it, since it is not a bug.

**Closed by andreyorst** 2018-04-11 12:31 UTC

**Comment by andreyorst** [comment] 2018-04-11 12:46
As a workaround I can suggest creating an `plain text.snippets` file, which contains standard Ultisnips facility - `extends tex`. Maybe it should be suggested to https://github.com/honza/vim-snippets as PR. I'm not LaTeX vim expert, so i don't know, maybe plaintex and tex are very different, and should use different snippets.
