### ISSUE TITLE
rogue "true" snippet appearing frequently

### ISSUE THREAD

**Issue by ludwj61** [SirVer/ultisnips#1291] opened 2020-11-03 20:51 UTC
When typing a period, ultisnips displays a useless snippet which just is the word "true", like this:
![image](https://user-images.githubusercontent.com/42984254/98038847-c71cb700-1deb-11eb-8a26-de482640cdc1.png)

**Steps to reproduce**

To make this happen for me is dependent on the language. Putting a period after anything in python and java, at least, causes that to occur. 
This happens with no snippets at all installed (just this repo; not any snippet repo).

-----

- **Operating System**: arch
- **Vim Version**: 
![image](https://user-images.githubusercontent.com/42984254/98039048-1531ba80-1dec-11eb-8dd2-acec2c7bfbf3.png)

- **UltiSnips Version**: most recent
- **Python inside Vim**: 3.8.6

**Comment by SirVer** [comment] 2020-11-04 06:39
@ludwj61 UltiSnips is not displaying such a menu ever, i.e. , you must have another plugin that does autocompletion popup or something like that. The problem is likely not with UltiSnips, but for sure I cannot reproduce your problem this without a full vim config and a repro case. Closing until this information is provided.

**Closed by SirVer** 2020-11-04 06:39 UTC
Labels: can't reproduce
