### ISSUE TITLE
Recursive expansion of snippets fails when on the 1st tabstop

### ISSUE THREAD

**Issue by lacygoill** [SirVer/ultisnips#931] opened 2018-02-03 18:55 UTC
I don't know whether UltiSnips is meant to support recursive expansion of snippets, but after reading `:h UltiSnips-capture-placeholder`, I was under the impression that it had the capability, provided that we use a single-character tab_trigger and the options `Ae` for a snippet which is meant to be expanded from another one.

---
Consider this snippet:

        snippet test
        ${1:foo} ${2:bar}
        endsnippet

And this 2nd snippet which should only be expanded when we're currently selecting a tabstop during the expansion of another snippet:

        snippet + "" "snip.last_placeholder" Ae
        ${1:baz} ${2:qux}
        endsnippet

If we insert `test` then press Tab to expand the snippet, we get:

    foo bar
    └─┤
      └ 1st tabstop of the 1st snippet is selected

While `foo` is selected, if we press `+` to expand a 2nd snippet, inside the 1st one, we get:

    baz qux bar
    └─┤
      └ 1st tabstop of the 2nd snippet is selected

But then, if we press `+` a 2nd time to expand a 3rd snippet, inside the other 2, there's no expansion; `+` is literally inserted inside the buffer, and we get:

    + qux bar

As a workaround,  we can press `Tab` then `S-Tab` to get back and forth between the 2 tabstops before pressing `+`. In this case, the 3rd snippet is correctly expanded:

    baz Tab S-Tab + qux bar
    →
    baz qux qux bar

**Comment by SirVer** [comment] 2018-04-13 21:33
I can reproduce, but I cannot say if this is a bug.

If you replace `snip.last_placeholder` through `True` like so:

~~~
snippet + "" "True" Ae
${1:baz} ${2:qux}
endsnippet
~~~

it does work for me. I am not sure about the semantics of `last_placeholder`, not sure if it behaves correctly or not. @seletskiy, can you have a look?

Can you outline what use case you try to solve? I do not understand the use case for the `snip.last_placeholder` at all.

**Comment by lacygoill** [comment] 2018-04-13 22:53
Hello,

> Can you outline what use case you try to solve?

I was not trying to solve a real problem, I was just reading the documentation, and to be sure I understood it correctly I tested various combinations of options and statements.

I stumbled upon this one which doesn't seem to work, so I wondered whether it was a bug or something I misunderstood. And if it was a bug, I thought it could be worth reporting it. If you consider it as not not a bug, or a minor one, feel free to close the issue; I understand your time is limited.

> I do not understand the use case for the snip.last_placeholder at all.

I could be wrong but IIRC I think `snip.last_placeholder` is a variable which contains the following properties:

    ┌────────────────────────────────────┬────────────────────────────────────────────────────┐
    │ snip.last_placeholder              │ last active placeholder from previous snippet      │
    ├────────────────────────────────────┼────────────────────────────────────────────────────┤
    │ snip.last_placeholder.current_text │ text in the placeholder on the moment of selection │
    ├────────────────────────────────────┼────────────────────────────────────────────────────┤
    │ snip.last_placeholder.start        │ placeholder start on the moment of selection       │
    ├────────────────────────────────────┼────────────────────────────────────────────────────┤
    │ snip.last_placeholder.end          │ placeholder end on the moment of selection         │
    └────────────────────────────────────┴────────────────────────────────────────────────────┘

The concept of previous snippet is only valid while you're expanding a snippet, because when you're not expanding a snippet `snip.last_placeholder` evaluates to `None`.

In the example mentioned above:

    snippet + "" "snip.last_placeholder" Ae
    ${1:baz} ${2:qux}
    endsnippet

The snippet is defined with the options `A` and `e`. `A` means that the snippet will be automatically expanded, but only if the expression between the second pair of double quotes evaluate to `True` (thanks to the `e` option).

`snip.last_placeholder` will evaluate to `None` when you're typing some text, without any text being expanded. In a test, `None` is the same as `False`, and thus when you press `+`, `+` is inserted literally in the buffer.

However, if you're currently expanding a snippet, then `snip.last_placeholder` will evaluate to an object with the properties `current_text`, `start` and `end`, which, in a test, is the same as `True`.
So, during the expansion of a snippet, if you press `+`, it will be expanded using the second snippet.

If you replace the expression with `True`, then it will always be true, and the second snippet will always be expanded, regardless of whether a snippet is being currently expanded.
IOW, when you press `+`, it will always be expanded. You'll never be able to insert `+` literally.

In practice, a condition such as `snip.last_placeholder` is probably not restrictive enough. For example, I have this simple snippet to expand an `if` block in VimL:

    snippet if "if statement" bm
    if $1
            ${2:${VISUAL}}
    ${4:${3:else}
            $0
    }endif
    endsnippet

But let's say I want an `if` block with not only an `else` statement, but also a previous `elseif` one.
I could define another snippet, but it would have two drawbacks:

 - you have to define a third snippet, a fourth one, ... for every block containing an additional `elseif` statement
 - you have to remember the tab_trigger for each of them

So, instead, I define only this second additional snippet:

    snippet i "elseif" "snip.last_placeholder and snip.last_placeholder.current_text == 'else'" Ae
    elseif $1
            $2
    ${3:else}
    endsnippet

Its purpose is to automatically add an additional `elseif` statement when you press `i`, but only while you're expanding a snippet and you're currently selecting the placeholder of a tabstop whose text is `else`.

This is due to the options `A` and `e`, which are used like in the snippet presented in the original issue.
Except this time, the condition is more restrictive; it's not a simple `snip.last_placeholder` anymore, instead it's:

    snip.last_placeholder and snip.last_placeholder.current_text == 'else'
    ├───────────────────┘     ├──────────────────────────────────────────┘
    │                         │
    │                         └ and only if I'm selecting the text `else`
    │
    └ only if I'm expanding a snippet

---

Btw, I think there's another related issue; sometimes the conditional snippet is not expanded even the first time its tab_trigger is pressed. Here's a MWE:

    snippet test "" bm
    ${1:foo} ${2:bar}${3:
    baz}
    endsnippet

    snippet + "" "snip.last_placeholder" Ae
    ${1:qux} ${2:norf}
    endsnippet

Insert `test`, press `Tab` to expand, and you'll get:

    foo bar
    baz

Now, press `Tab` two additional times, so that you jump to the third tabstop `baz`.
Finally, while `baz` is selected, press `+`. `+` should be automatically expanded into `qux norf`, but instead it's inserted literally.

Maybe the newline inside the placeholder is part of the issue.

If you add a space before the third tabstop, the issue disappears. IOW, these snippets work as expected:

    snippet test "" bm
    ${1:foo} ${2:bar} ${3:
    baz}
    endsnippet

    snippet + "" "snip.last_placeholder" Ae
    ${1:qux} ${2:norf}
    endsnippet

---

Again feel free to close the issue if you think it's not important.
Thank you very much @Sirver, @seletskiy for your work on the plugin.

**Comment by SirVer** [comment] 2018-04-15 11:08
Thanks for the explanation. I do understand the concept behind the `context` triggers, I just do not understand the semantics of `snip.last_placeholder`, so I cannot say if this is a bug or not. @seletskiy Needs to weigh in.

**Comment by SirVer** [comment] 2019-10-30 20:59
Since this is not a real problem where a potential solution for a real problem is not working and we do not have full clarity if `snip.last_placeholder` is working as intended or not, I'll go ahead and close this issue out. Let me know if you disagree.

**Closed by SirVer** 2019-10-30 20:59 UTC
Labels: pending feedback
