### ISSUE TITLE
YouCompleteMe breaking Snippets Loaded Later

### ISSUE THREAD

**Issue by adam-beck** [SirVer/ultisnips#700] opened 2016-05-13 16:13 UTC
I originally posted this in [vim-snippets](https://github.com/honza/vim-snippets/issues/733#issuecomment-219083095). But basically when I have vendor scripts, or scripts not loaded off the bat, I cannot get them to trigger and YouCompleteMe seems to be breaking this.

When working with the vendor snippets I have tried three different methods one-by-one to get them loaded: adding a command to an ftplugin/ file, running the  `UltiSnipsAddFiletypes` command from vim, and adding the `autocmd` command to my ~/.vimrc. They all seem to work when I don't have the YouCompleteMe plugin enabled. However, when I enable it the ftplugin/ and ~/.vimrc methods no longer work. I can still run the command in vim itself and get the snippets but they are not provided in the YouCompleteMe suggestion list.

[Here is a link to my vimrc](https://github.com/adam-beck/dotfiles/blob/master/home/.vimrc). I had changed the order of when the snippets were loaded vs YCM but it didn't seem to matter.

OS: Ubuntu 14.04
Vim: 7.4.1829 compiled with Python 2.7.6
Latest versions of YouCompleteMe, Ultisnips, and vim-snippets

Expected
When adding :UltiSnipsAddFiletypes javascript-jasmine to ~/.vim/ftplugin/javascript.vim I should see a list of available Jasmine snippets in the suggestion list. Even without the list, I should be able to type the snippet (def for example) and then activate the UltiSnipsExpandTrigger to see the completed snippet.

Actual
Using the UltiSnipsExpandTrigger I do not get a completed vendor snippet.

Notes:
This may be a YCM issue but was hoping somebody might have some advice. Also, the snippets work as expected when they don't need to be loaded (i.e. non-vendor snippets).

**Comment by seletskiy** [comment] 2016-05-16 08:16
@adam-beck: Does that newly added snippets got expanded?

**Comment by adam-beck** [comment] 2016-05-16 11:50
@seletskiy if I understand what you are asking, yes. When I run `UltiSnipsAddFiletypes javascript-jasmine` the snippets will expand. But I must do this every time I open a javascript file and the snippets also don't appear in the YCM list.

**Comment by Kjir** [comment] 2016-06-15 09:36
I'm having this issue as well. The snippets used to work, but at some point, quite some time ago, things did not work anymore. If I manually run `UltiSnipsAddFiletypes javascript-jasmine` the snippets are loaded and - while not detected by YCM - will work as expected.
I also confirm that disabling YCM will automatically load the snippets.

**Comment by SirVer** [comment] 2018-04-01 20:10
I cannot reproduce this - I use YCM daily and all my snippets work.

Please post a minimal repro case. Closing as non-actionable till then.

**Closed by SirVer** 2018-04-01 20:10 UTC
Labels: possible bug, wontfix (can't reproduce)
