### ISSUE TITLE
i_ctrl-i

### ISSUE THREAD

**Issue by aloispichler** [SirVer/ultisnips#1515] opened 2023-01-13 13:51 UTC
What is ultisnips doing with `i_Ctrl-i`???
With ultisnups plugged in, I cannot
`inoremap <C-i> <nop>`.
The docs don't say a word about `i_Ctrl-i`.
Thanks!

**Comment by SirVer** [comment] 2023-02-01 19:50
Duplicate of #1212. tl;dr: Terminal emulators make no difference between `<tab>` and `<ctrl-i>`, it is the same to them. This has nothing to do with UltiSnips.

**Closed by SirVer** 2023-02-01 19:50 UTC
