### ISSUE TITLE
Interpolation - Undefined Variable

### ISSUE THREAD

**Issue by msmall-amfam** [SirVer/ultisnips#769] opened 2016-10-04 21:13 UTC
When attempting interpolation (bash or python), I receive an undefined error. Am I missing something that enables shell and/or python interpolation? 

In the case of a shell snippet such as:

```
snippet testing
    `echo 'hello'`
```

Yields:

```
An error occured. This is either a bug in UltiSnips or a bug in a                                                            
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 138, in expand_or_jump
    rv = self._try_expand()
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 718, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 673, in _do_snippet
    None, start, end)
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 442, in launch
    snippet_instance.update_textobjects()
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 80, in update_textobjects
    if obj._update(done):
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_viml_code.py", line 20, in _update
    self.overwrite(_vim.eval(self._code))
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 121, in eval
    rv = vim.eval(as_vimencoding(text))
error: Vim:E121: Undefined variable: echo
```

In the case of a python snippet such as:

```
snippet testing
    `!p print 'hello'`
```

Yields:

```
An error occured. This is either a bug in UltiSnips or a bug in a                                                            
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 138, in expand_or_jump
    rv = self._try_expand()
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 718, in _try_expand
    self._do_snippet(snippet, before)
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 673, in _do_snippet
    None, start, end)
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 442, in launch
    snippet_instance.update_textobjects()
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 80, in update_textobjects
    if obj._update(done):
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/_viml_code.py", line 20, in _update
    self.overwrite(_vim.eval(self._code))
  File "/home/mcs041/.vim/bundle/ultisnips/pythonx/UltiSnips/_vim.py", line 121, in eval
    rv = vim.eval(as_vimencoding(text))
error: Vim:E121: Undefined variable: p
```

My .vimrc:

```
set nocompatible                                                                                                             
filetype off 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'SirVer/ultisnips'
call vundle#end()
filetype plugin indent on

syntax on

set number
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set cursorline
set showmatch

colorscheme molokai

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
```

My `vim --version`:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     +tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
```

**Comment by dylnmc** [comment] 2016-10-11 03:27
I ran into the same problem. I opened/closed an issue a few weeks ago for the same reason. This was the only way that I could possibly get UltiSnips to work correctly (basic vimrc) - I hope it helps.

```
call plug#begin('~/.vim/plugged')
Plug 'SirVer/ultisnips'
call plug#end()
let g:UltiSnipsSnippetDirectories=['~.vim/Ultisnips']
```

If you look at the `let g:UtliSnipsSnippetDirectories=[...]`, then you will notice that I set the dir to `~.vim/Ultisnips`. This is absolutely ridiculous considering the fact that it should be `~/.vim/Ultisnips` and should even support `.vim/Ultisnips`. I haven't looked at the code, but I am quite certain the problem is that UltiSnips (when you use `:UltisnipsEdit`) writes the snippet files to the wrong dir, and then when you try to key-complete the snippet, UltiSnips reads from a different dir.

Even that doesn't make much since since UltiSnips actually calls the right snippet yet yields an error!!! (I was getting the same error.) Something is gravely wrong here, but hopefully my minimal vimrc will help you.

By the way, people in chat.freenode.net on #vim could not reproduce this, and I am on arch. Additionally, I tried using `gvim` (from arch repos) and `nvim` (from AUR), so it seems it's not just vim that is misbehaving, but rather the plugin.

**Comment by dylnmc** [comment] 2016-10-11 03:52
I got the same error until I removed everything regarding snippets, and then used `g:UltiSnipsSnippetDirectories = ['UltiSnips']`  (even thought that is set by default).

Try this. Remove everything about snippets (back up everything first if you want), start with that vimrc you have and add the code highlighted above. Then try this...

```
vim test.txt
:UltiSnipsEdit
<insert>
plugin date
date: `!v strftime('%c')`
endplugin
</insert>
:w
:bn
<insert>
date<tab>
</insert>
```

see if that works. This worked for me. It took me a few hours actually to go through a lot of different iterations and to try to figure out what was going wrong.

**Comment by ericfirth** [comment] 2016-10-22 18:25
I am getting the same issue, python interpolation isn't working at all for me. Tried dylnmc's trick and nothing.

**Comment by msmall-amfam** [comment] 2016-10-24 13:48
Soor @dylnmc, didn't work. Tab activation doesn't seem to fire when I attempt your suggestion.

**Comment by seletskiy** [comment] 2016-11-15 09:43
The reason is that you're using old snipmate syntax.

Try that one:
```
snippet test "test"
`!p snip.rv = "hello"`
endsnippet
```

Snippet **should not** be placed in the `snippet/` subdirectory, it's reserved for snipmate-syntax snippets.

**Comment by dylnmc** [comment] 2017-06-20 03:02
This just throws an error whenever I load a file with particular filetype. E.g., if I create

```
snippet banana "test"
`!p snip.rv = "I'm a banana"`
endsnippet
```

in my `vim-snippets/snippets/python.snippets`, then I get this error:

```
UltiSnips.snippet.source.file._base.SnippetSyntaxError: Invalid line '`!p snip.rv = "I\'m a banana"`' in ~/.vim/plugged/vim-snippets/snippets/python.snippets:2
```

Am I doing something wrong now? :rofl:

**Comment by dylnmc** [comment] 2017-06-20 03:52
@seletskiy this worked for me after I modified vimrc like so:

```vim
let g:UltiSnipsSnippetsDir          = $HOME.'/.vim/UltiSnips/'
let g:UltiSnipsSnippetDirectories   = [ "UltiSnips" ]
```

This actually worked! I finally sat down for an hour and figured out this darn ultisnips. I have been using the `vim-snippets` from `honza`, but I hadn't started using the new syntax. Kewl beanz. Now the following works!

```vim
snippet banana "test"
${1:100} / ${2:100} ==> `!p
try: snip.rv = float(t[1]) / float(t[2])
except: pass`$0
endsnippet
```

**Comment by andreyorst** [comment] 2018-04-12 15:18
Closing this as solved. Reopen if needed.

**Closed by andreyorst** 2018-04-12 15:18 UTC
Labels: pending feedback, traceback
