### ISSUE TITLE
I have installed UltiSnips through pathogen on four machines.  Three of the four display error

### ISSUE THREAD

**Issue by sgarrison05** [SirVer/ultisnips#1142] opened 2019-11-16 02:36 UTC
**Expected behavior:**

No Error

**Actual behavior:**

Error detected while processing function UltiSnips#Edit:
line    6:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sgarrison/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 848, in _file_to_edit
    return _select_and_create_file_to_edit(potentials)
  File "/home/sgarrison/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 73, in _select_and_creat
e_file_to_edit
    file_to_edit = potentials.pop()
KeyError: 'pop from an empty set'

**Steps to reproduce**

~/.vim/

mkdir bundle && git clone https://github.com/sirVer/ultisnips

I have added the corrrect lines in my .vimrc

1. inside vim :UltiSnipsEdit
2.
3.

-----

- **Operating System**: 
- **Vim Version**: 
- **UltiSnips Version**: 
- **Python inside Vim**: 
- **Docker repo/vimrc**:

**Comment by SirVer** [comment] 2019-11-16 20:25
I am sorry that you see this bug, however I cannot reproduce with the given information: This bug report lacks a vimrc (`I have added the corrrect lines in my .vimrc` is insufficient) a repro case, an OS version, python version, and vim version. Closing until these information are provided.

**Closed by SirVer** 2019-11-16 20:25 UTC

**Comment by sgarrison05** [comment] 2019-11-16 20:28
I’ll provide them. 

Shon Garrison
Email: sgarrison05@sbcglobal.net

**Comment by sgarrison05** [comment] 2019-11-16 21:16
I have never posted before so I was unsure all I needed to provide.   I am providing the missing pieces hopefully, including my .vimrc.  When I said I have added the correct line, I meant that I copied and pasted the commands provided in the quickstart.

**Comment by trivender** [comment] 2019-12-18 09:04
Same error.. I installed via pathogen. 

![image](https://user-images.githubusercontent.com/1558981/71071909-7d12ee80-21a3-11ea-96a1-8a34a06c5f91.png)

**Comment by SirVer** [comment] 2019-12-18 09:32
@trivender Same statement: Unsufficient information to reproduce the problem.

Please provide a fully reproducible example, ideally using the approach explained in https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs or if not possible with a minimal `vimrc` and snippets files and an exact sequence of key strokes that trigger the bug.

In the meantime I added a better error message for the case you guys are seeing. It will not remove the error, but maybe make the problem less cryptic to users.

**Comment by trivender** [comment] 2019-12-18 09:49
I escaped the error by looking at the function definition and calls. I think program was not able to locate directory having snippets. I read more in   4.1.1 How snippets are loaded  here [https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt] . This made me to try to add below in my .vimrc file.

let g:UltiSnipsSnippetDirectories=[$HOME.'/Vim/vimfiles/bundle/vim-snippets/UltiSnips']

Note: I am also using : //github.com/honza/vim-snippets.git

I no longer have error and it now opens all.snippets. At least I now do not have error. I will explore it further.
