### ISSUE TITLE
JumpBackward map isn't working

### ISSUE THREAD

**Issue by llfm** [SirVer/ultisnips#543] opened 2015-08-07 00:05 UTC
Hello,

Using this minimal vim, the backward trigger doesn't go back.
```vim
set nocompatible
filetype indent on

call plug#begin('~/.vim/plugged')
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
call plug#end()

let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<c-z>"
```
The problem isn't the keystrokes, because if I change it with `forward` it works.

Vim version: 7.4-1-778
URXvt: 9.21
How can I give more information?

**Comment by SirVer** [comment] 2015-08-07 05:55
I cannot reproduce this with my setup. According to the plug readme you can drop the first two lines in your vimrc - does that make a difference?

Which snippet are you testing with?

**Comment by llfm** [comment] 2015-08-07 12:16
> Which snippet are you testing with?

Now I got the problem.
When using a snipmate snippet, it doesn't go back. This is supposed to work?

e.g. snippet `if` in a `c` file.

**Comment by SirVer** [comment] 2015-08-07 20:39
so you are using this snippet? https://github.com/honza/vim-snippets/blob/master/snippets/c.snippets#L54

if so, that is working as intended: as soon as you reach the $0 tabstop, you can no longer jump back: the snippet is exited. 

this is a performance optimization: if you would just continue to type in $0 and the snippet would still be active, UltiSnips would continue to diff your buffer on every keystroke you type - rather performance intensive. 

Closing for now - please speak up if you still see a bug.

**Closed by SirVer** 2015-08-07 20:39 UTC

**Comment by llfm** [comment] 2015-08-07 20:58
So why this snippet works? 
https://github.com/honza/vim-snippets/blob/master/UltiSnips/php.snippets#L64.

Seems to be the same case.

**Comment by SirVer** [comment] 2015-08-08 06:31
No, it is not the same case. The snippet you link contains $1 and $2 - if you jump one more (to the end of the snippet, the implicit $0) it will also exit and you can no longer go back.

The same logic is used for UltiSnips snippets too - so no, you cannot go back when you use ultisnips snippets once you hit $0.

**Comment by llfm** [comment] 2015-08-09 02:51
The code isn't the same, but the logic is conflicting with what you said.
Why is the `c` snippet a performance optimization and the `php` not?

**Comment by SirVer** [comment] 2015-08-10 05:18
the php snippet is just wrong - it should follow the idea of the `c` snippet. 

Go ahead and try it yourself: Copy a long text (like a web page), then insert the c snippet till you reach `$0` and paste -> you can insert.

do the same for the php one -> Vim will take 100% and likely hang forever.

**Comment by llfm** [comment] 2015-08-10 17:49
Thank you for the explanation.

I don't know how long is a long text for _me_, but I think it's more likely that _I_ want to go back than writing or pasting a long text. Maybe I'll create an issue to `honza`, for consistency in the snippets.
