### ISSUE TITLE
UltiSnips crashes when inserting long lines (MemoryError)

### ISSUE THREAD

**Issue by Oberon00** [SirVer/ultisnips#402] opened 2014-11-20 17:32 UTC
When I tried inserting the output of a SQL-Select into a LaTeX file, gVim first froze and then, after some time, I got the following error:
```
Traceback (most recent call last):
  File "C:\Users\Christian\vimfiles\bundle\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 54, in wrapper
    return func(self, *args, **kwds)
  File "C:\Users\Christian\vimfiles\bundle\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 301, in _cursor_moved
    es = diff(lt, ct, initial_line)
  File "C:\Users\Christian\vimfiles\bundle\ultisnips\pythonx\UltiSnips\_diff.py", line 160, in diff
    while len(d[cost]):
MemoryError
```

The text I tried to paste is [here][gist] (the data is from the Sakila sample database, so nothing confidential). There are just 46 lines, but each is 256 characters long (consisting mostly of trailing spaces).

Peak working set  of gVim was 1,835,960K. I ran into this bug on Windows 8.1 x64, but with a 32 Bit Vim.

[gist]: https://gist.github.com/Oberon00/b96a200490f07ce39416#file-sakila-unavailable-films-out

**Comment by SirVer** [comment] 2015-07-11 16:54
Dupe of #155 actually.

**Closed** 2015-07-11 16:55 UTC
Labels: maybe_in_neovim
