### ISSUE TITLE
No Snippet Expansions Work ...

### ISSUE THREAD

**Issue by psacawa** [SirVer/ultisnips#1081] opened 2019-05-09 22:35 UTC
**Expected behavior:**

Expanding snippets works.

**Actual behavior:**

Basic snippet expansion and listing all snippets does nothing, though by placing lines of debug output throughout the source I'm able to verify that `UltiSnips_Manager` is initialized and `python3` is recognized. `:UltiSnipsEdit` works.

Running `~/.vim/bundle/UltiSnips/test_all.py -v` causes the test suite to enter the first test and stall, wtih SIGTERM output as below:
```
runTest (test_Format.FOSimple_Break_ExpectCorrectResult) ... ^CTraceback (most recent call last):
  File "./test_all.py", line 162, in <module>
    sys.exit(main())
  File "./test_all.py", line 160, in main
    failfast=options.exitfirst).run(suite).wasSuccessful()
  File "/home/psacawa/anaconda3/lib/python3.6/unittest/runner.py", line 176, in run
    test(result)
  File "/home/psacawa/anaconda3/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/psacawa/anaconda3/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/home/psacawa/anaconda3/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/home/psacawa/anaconda3/lib/python3.6/unittest/case.py", line 601, in run
    self.setUp()
  File "/home/psacawa/.vim/bundle/UltiSnips/test/vim_test_case.py", line 180, in setUp
    self.in_vim_python_version = self.vim.launch(vim_config)
  File "/home/psacawa/.vim/bundle/UltiSnips/test/vim_interface.py", line 157, in launch
    wait_until_file_exists(done_file)
  File "/home/psacawa/.vim/bundle/UltiSnips/test/vim_interface.py", line 19, in wait_until_file_exists
    time.sleep(interval)
KeyboardInterrupt
```

**Steps to reproduce**

Minimal `.vimrc`

```
set nocompatible 
" filetype off 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'sirver/UltiSnips'
call vundle#end()

filetype on
filetype plugin on

let g:UltiSnipsExpandTrigger='<leader>e'
let g:UltiSnipsListSnippets='<leader>g'
```
In `location/test.cpp`:
```
int main () { return 0; }
```
`set ft?` yields `filetype=cpp`.
Running `:UltiSnipsEdit` opens `location/UltiSnips/cpp.snippets`, which contains
```
snippet asdf "test"
hello
endsnippet
```

**Key Sequence**
Enter insert mode on new line and enter `asdf<leader>e` to expand does nothing (but some python code is run). This is also true for `<leader>g` in insert mode, which should list all snippets.

**What Else I've Tried and Didn't Work**

- Default / different keys ( same thing happens with `<tab>` and `<c-tab>`)
- Running from a terminal with no `.bashrc`
- Using a different installation of `python3`
- Different filetypes: `.tex`, `.py`, ...
- Different settings in `.vimrc`

-----
- **Operating System**: Ubuntu 18.04
- **Vim Version**: 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Zadane łaty: 1-1453
Zmieniony przez pkg-vim-maintainers@lists.alioth.debian.org
Skompilowany przez pkg-vim-maintainers@lists.alioth.debian.org
Olbrzymia wersja z GTK2 GUI.  Opcje włączone (+) lub nie (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    +tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua               +ruby              +X11
+dialog_con_gui    +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             +xim
+digraphs          +modify_fname      +smartindent       +xpm
+dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
       vimrc systemu: "$VIM/vimrc"
   vimrc użytkownika: "$HOME/.vimrc"
 2-gi plik vimrc użytkownika: "~/.vim/vimrc"
    exrc użytkownika: "$HOME/.exrc"
     gvimrc systemu: "$VIM/gvimrc"
  gvimrc użytkownika: "$HOME/.gvimrc"
2-gi plik gvimrc użytkownika: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
 systemowy plik menu: "$VIMRUNTIME/menu.vim"
   odwet dla $VIM-a: "/usr/share/vim"
Kompilacja: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-NQEcoP/vim-8.0.1453=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Konsolidacja: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm     
```

- **UltiSnips Version**: 
`1a99766b73783bafb08cfa07d7e29e5387c55189 ` (present master branch)
- **Python inside Vim**: 
`3.6.7 (default, Oct 22 2018, 11:32:17)`

Any insight into what's going on is highly appreciated, I'd really be delighted to make use of this probably wonderful plugin.

**Comment by lacygoill** [comment] 2019-05-10 19:14
You didn't specify the location of your snippet files.

If they're located under `/path/to/dir`, then add to your vimrc:

    let g:UltiSnipsSnippetDirectories = ['/path/to/dir']

**Comment by psacawa** [comment] 2019-05-10 19:34
Hi, and thank you for your response.
Running `let g:UltiSnipsSnippetDirectories` yields `g:UltiSnipsSnippetDirectories ['UltiSnips'] `, the default option. Correspondingly, the snippet file above is in `location/UltiSnips/cpp.snippets`.
I guess the fact that `UltiSnipEdit` opens the right file implies there is no problem with the plugin recognising it?

**Comment by lacygoill** [comment] 2019-05-10 20:19
> The default configuration for this variable did not work for me. Does it work for others?

I don't know. According to the documentation, the plugin should look for the snippet files in each `UltiSnips` subdirectory of a directory in the runtimepath (`:echo &rtp`).
If it didn't work for you, maybe it was because your snippets directory was not in the rtp.

Again, I don't know, I've always used `g:UltiSnipsSnippetDirectories` with a single absolute path; it works, and I don't need/want more.

> If not, then maybe this information ought to be added to the readme to make startup more convenient? If you like, I can submit a PR.

I'm not the owner of the repo, just a contributor, so if you feel like writing a PR is warranted, then do it.

---

This is unrelated to your issue, but you don't need this line in your vimrc:

    filetype on

Because the filetype detection mechanism is already enabled by the next line:

    filetype plugin on

You don't need this line either:

    set nocompatible

Because Vim starts in non-compatible mode when it detects a vimrc.
The only case where it could be useful, is when you start Vim with `-u`; but even then you can use `-Nu`, so you still don't really need `set nocompatible`.

---

In the future, if your snippets don't expand, start Vim with a minimal vimrc and a test snippet:

        $ mkdir /tmp/snippets

        $ cat <<'EOF' >/tmp/snippets/vim.snippets
        snippet trigger
        my snippet has been expanded
        endsnippet
        EOF

        $ cat <<'EOF' >/tmp/vimrc
        let g:UltiSnipsSnippetDirectories = ['/tmp/snippets']
        let g:UltiSnipsExpandTrigger = '<tab>'
        set rtp-=$HOME/.vim
        set rtp^=$HOME/.vim/bundle/ultisnips
        set rtp+=$HOME/.vim/bundle/ultisnips/after
        set rtp^=$HOME/.vim
        set vi=
        filetype plugin on
        EOF

        $ vim -Nu /tmp/vimrc +"put ='trigger'" +'startinsert!' /tmp/vim.vim

The first command creates a temporary directory for the test snippet.  
The second command creates a test snippet.  
The third command creates a minimal vimrc.  
The last command starts Vim with the minimal vimrc. The `+"put ='trigger'"` makes Vim write the word `trigger` in the Vim buffer (see `:h -+c` and `:h :put`). And `:startinsert!` makes Vim enter insert mode at the end of the line (see `:h startinsert`).

Then, press Tab; if the snippet is not expanded:

 - something is wrong in your Vim build (try to recompile a more recent version with more features)
 - something is wrong in your UltiSnips plugin (make sure it's correctly installed)
 - something in your environment intercepts the Tab keypress before Vim (terminal emulator, window manager, ...)

If it is expanded, you have a working starting point.
From there, progressively re-include your Vim settings and your snippets, until something breaks. When that happens, restart Vim with the previous minimal vimrc, and add the last setting which broke the expansion. If the new – augmented – vimrc reproduces your issue, then  you have a [MCVE](https://stackoverflow.com/help/mcve), which you can post in an issue to get more help.

**Comment by psacawa** [comment] 2019-05-10 21:07
Regarding the unneeded lines - these were lines I got from various documentations throughout the years, which I decided to leave in case Vundle requested them. But thank you for your advice, I'll try to find the root of the original issue.

**Comment by jmarceli** [comment] 2019-05-24 10:38
Hi, I was having a similar problem and in my case replacing `~/.vim/UltiSnips` with absolute path `/Users/myusername/.vim/UltiSnips` solves the issue.

**Comment by SirVer** [comment] 2019-10-20 20:24
I see that onboarding in UltiSnips could still be improved after all these years :(. Closing this issue as it seems to not contain anything actionable anymore.

**Closed by SirVer** 2019-10-20 20:24 UTC
