### ISSUE TITLE
A problem about visual placeholder

### ISSUE THREAD

**Issue by HP-Li** [SirVer/ultisnips#1242] opened 2020-06-12 06:30 UTC
Hello sir, I encountered a problem of ${VISUAL}.
**Expected behavior:**

 I selected some text, but when I use the Visual Placeholder, it always lost last character. Example, I selected "abc", I want  ${VISUAL} show "abc".

**Actual behavior:**
But it only show "ab" , the last character is missing. I use paste to check it, it's complete.

**Steps to reproduce**

-----

- **Operating System**: Ubuntu 20.04
- **Vim Version**: 8.1
- **UltiSnips Version**: 
- **Python inside Vim**: 3.8.2
- **Docker repo/vimrc**:

**Comment by anihm136** [comment] 2021-02-12 03:49
This could be due to your vim settings. Try `:set selection=inclusive` and see if it works?

**Comment by HP-Li** [comment] 2021-03-11 11:53
> This could be due to your vim settings. Try `:set selection=inclusive` and see if it works?

I'm sorry, it doesn't work

**Comment by HP-Li** [comment] 2021-03-11 11:59
> This could be due to your vim settings. Try `:set selection=inclusive` and see if it works?

 the last character is disappeared, doesn't unselected.

**Comment by sprnza** [comment] 2021-04-30 10:07
Hi @HP-Li I'm facing the same issue. Have you managed to find a solution?

**Comment by SirVer** [comment] 2021-05-01 05:43
@HP-Li @sprnza

From this information alone, we cannot track this bug down, since we cannot reproduce.

Please provide a fully reproducible example, ideally using the approach explained in https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs or if not possible with a minimal `vimrc` and snippets files and an exact sequence of key strokes that trigger the bug.

**Comment by SirVer** [comment] 2021-05-18 14:24
Closing due to not being able to repro with the information provided.

**Closed** 2021-05-18 14:24 UTC
Labels: can't reproduce, triaged, wontfix
