### ISSUE TITLE
Python Interpolation inconsistent behavior

### ISSUE THREAD

**Issue by horseinthesky** [SirVer/ultisnips#1323] opened 2021-03-13 09:25 UTC
Hello.
I am new to the tool and not sure if I do something wrong or if is supposed to be so.

**Expected behavior:**
1) Expand via dropdown menu and expand key should works the same way.

**Actual behavior:**

**Steps to reproduce**
Here is python snippet from the [(( screencast))](http://vimcasts.org/episodes/ultisnips-python-interpolation/):
```
global !p
def fraction(a, b):
    try:
        return "%.1f" % (float(a)/float(b))
    except (ValueError, ZeroDivisionError):
        return "ERR"
endglobal

snippet 75wrds "Log a 750words.com session" b
750words.com: ${1:750} words in ${2:20} minutes - `!p
snip.rv = fraction(t[1], t[2])
` wpm.
endsnippet
```

And my init.vim:
```
Plug 'SirVer/ultisnips'  
Plug 'honza/vim-snippets'

let g:UltiSnipsExpandTrigger='<C-s>'      
let g:UltiSnipsJumpForwardTrigger='<C-j>' 
let g:UltiSnipsJumpBackwardTrigger='<C-k>'
```

The inconsistency happens when I expand snippet:
1) If I expand via picking snippet from the dropdown menu:
![image](https://user-images.githubusercontent.com/19948672/111025121-561d8980-83f3-11eb-9487-2032cd583b7c.png)
I get ERR and snippet doesn't react on changing ${1} or ${2}.
![image](https://user-images.githubusercontent.com/19948672/111025163-82d1a100-83f3-11eb-86be-b7b29b719b7c.png)
2)  If I expand via `<C-s>` everything works fine:
![image](https://user-images.githubusercontent.com/19948672/111025212-b8768a00-83f3-11eb-8a13-19a29cfcf89c.png)
I can change ${1} or ${2} and it changes the result.

Second example:
```
global !p
def token():
    import secrets
    return secrets.token_hex(16)

def h(token):
    import hashlib
    return hashlib.sha256(token.encode('utf-8')).hexdigest()

endglobal

snippet token "token" !b
${1:username}: ${2:`!p if not snip.c: snip.rv = token()`}
`!p if not snip.c: snip.rv = h(t[2])`: ${1: username}
endsnippet
```

1) If I expand via the dropdown menu it somehow calculates the hash value from the word `username` but not from the token value (${2}) provided. Moreover, I can edit `username` but the hash value is not changing:
![image](https://user-images.githubusercontent.com/19948672/111025512-b01f4e80-83f5-11eb-82c8-51881935fe7d.png)

2) Expand via `<C-s>` it does calculate hash correctly but jumps on the end of the expanded snippet and doesn't let we edit it (`<C-j/k>` do nothing)
![image](https://user-images.githubusercontent.com/19948672/111025458-5585f280-83f5-11eb-97f3-73183035be50.png)

-----

- **Operating System**: `ubuntu 20.04`
- **Vim Version**:
```
NVIM v0.4.3
Build type: Release
```
- **UltiSnips Version**: `66d81fc2c0bda30be69fffa46da0932ee8d5ddd5` installed via vim-plug
- **Python inside Vim**:
```
3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0]
```

**Comment by SirVer** [comment] 2021-03-13 14:37
I have a few problems with this bug report:

1. UltiSnips and Vim has no drop down menu, so I have no idea what that component is and why it might give you trouble.
2. There is no full repro vimrc here and for me the example snippet is working well with the small provided snippet. Init.vim is a nvim concept I assume?
3. This is a bug report for neovim, which is notoriously creating issues in our bug tracker with not being compatible with Vim's python implementation. Can you repro with vanilla Vim?

**Comment by horseinthesky** [comment] 2021-03-13 15:51
@SirVer I'm sorry for possibly naming things not by their names.
1) Drop down menu == popup (ins-completion) menu
```
pumvisible()                                            pumvisible()         
                Returns non-zero when the popup menu is visible, zero        
                otherwise.  See ins-completion-menu.                         
                This can be used to avoid some things that would remove the  
                popup menu.                                                  
```

By pressing CRTL-X CTRL-N to show completions I don't see any snippets
![image](https://user-images.githubusercontent.com/19948672/111035474-d52eb400-842b-11eb-8f52-44eb11d4a4cc.png)

So I cannot reproduce the example #1 issue in vanilla VIM.

But example #2 issue persists in vanilla VIM:
![image](https://user-images.githubusercontent.com/19948672/111035593-3e162c00-842c-11eb-9e57-0358f5c6a442.png)
1) Cursor jumps on the end of expanded snippet (I marked it with red).
2) Changing of `username` under cursor doesn't change first `username` (on the first line).
3) Changing token value (first line after the colon) doesn't change the hash value (second line before the colon).

This is my vanilla VIM .vimrc:
```
call plug#begin('~/.vim/plugged')
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
call plug#end()

let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<C-j>'
let g:UltiSnipsJumpBackwardTrigger='<C-k>'
```

And this is my python.snippet file:
```
global !p
def token():
    import secrets
    return secrets.token_hex(16)

def h(token):
    import hashlib
    return hashlib.sha256(token.encode('utf-8')).hexdigest()

endglobal

snippet token "token" !b
${1:username}: ${2:`!p if not snip.c: snip.rv = token()`}
`!p if not snip.c: snip.rv = h(t[2])`: ${1:username}
endsnippet
```

**Comment by SirVer** [comment] 2021-03-16 20:10
That clears up the confusion about the first issue, this is indeed NeoVim only. I have no idea what feature enables it to show snippets, but apparently that integration is buggy, since it seems to trigger the snippets differently. I will add the default closing reasons for why this will not be fixed until a hero steps forward to help iron out the NeoVim/UltiSnips interactions.

As for your second issue: Your snippet contains invalid code, more specfically you define your Tabstop No1 multiple times which is not defined. If you change your snippet to either read:

 ```
snippet token "token" !b
${1:username}: ${2:`!p if not snip.c: snip.rv = token()`}
`!p if not snip.c: snip.rv = h(t[2])`: $1
endsnippet
```

or 

```
snippet token "token" !b
$1: ${2:`!p if not snip.c: snip.rv = token()`}
`!p if not snip.c: snip.rv = h(t[2])`: ${1:username}
endsnippet
```

i.e. turn one tabstop definition into a mirror definition, your snippet should work.

**Closed by SirVer** 2021-03-16 20:10 UTC
Labels: can't reproduce, neovim only, pending feedback, triaged

**Comment by horseinthesky** [comment] 2021-03-17 07:42
Mirroring the definition actually does nothing with the issue.

In case of
```
snippet token "token" !b
${1:username}: ${2:`!p if not snip.c: snip.rv = token()`}
`!p if not snip.c: snip.rv = h(t[2])`: $1
endsnippet
```
1) It still jumps on the second entry of ${1} which is now empty
![image](https://user-images.githubusercontent.com/19948672/111431324-b3c01780-870c-11eb-8824-c9b8e536549d.png)
2) It won't jump on the first entry of ${1} via <C-j> or <C-k>.
3) When jumping on ${2} (token value) and changing it the hash value remains the same.
![image](https://user-images.githubusercontent.com/19948672/111431741-377a0400-870d-11eb-91bc-6c8042e3a6df.png)

I assume this kind (3) of calculation can't be done via UltiSnips but 1 and 2 seem like an UltiSnips bug.

**Comment by SirVer** [comment] 2021-03-18 08:17
1. + 2.: I cannot reproduce this, it works for me (Vanilla Vim, recent git. latest UltiSnips from master): https://asciinema.org/a/bjPmsZJm6FQ5cY20yNRY9KYcU. I guess you will need to provide a repro case within the docker container as [documented here](https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs). 

3. That seems to be a bug in your code: you ask ultisnips to only change the value if `snip.c` is not set, i.e. the first time it comes by this place. So it will not update the value anymore. If you change your snippet to

```
snippet token "token" !b
${1:username}: ${2:`!p if not snip.c: snip.rv = token()`}
`!p snip.rv = h(t[2])`: $1
endsnippet
```

it works for me.

**Comment by horseinthesky** [comment] 2021-03-18 11:39
@SirVer 
3 works great. Thank you.

Repro case or 1 and 2 is in the fork branch https://github.com/horseinthesky/ultisnips/tree/issue_1323
https://asciinema.org/a/5HTL14w2XBgYuhHGtz5TUzGHS

Don't know why but I wasn't able to make <C-j>/<C-k> work.
The main issue with jumping on ${1} second entry remains the same.

**Comment by SirVer** [comment] 2021-03-18 13:53
@horseinthesky Your snippet contains a typo: `${1}` is not a mirror, it is a tabstop, i.e. you are defining `${1}` twice. Try using `$1` instead on the second position, like I have done in my prior comment: https://github.com/SirVer/ultisnips/issues/1323#issuecomment-801724759

**Comment by horseinthesky** [comment] 2021-03-18 15:21
@SirVer Ah, everything working perfectly fine now. Thank you.
I'm sorry for spending so much of your time. My silly mistake.

**Comment by SirVer** [comment] 2021-03-18 17:15
@horseinthesky No worries. Glad that things are worked out.

Spending time rarely is the issue as long as the bug reporters (you in this case) keep moving the issue forward. You've done that really well, including providing a repro case that made it very easy and fast to diagnose the problem you were facing. It was a pleasure helping out! Sorry that I could not help with the NeoVim issue, but as long as nobody really takes ownership of UltiSnips + NeoVim I feel the support there will not improve.

**Comment by horseinthesky** [comment] 2021-03-18 18:52
I would like to know more but sadly at the moment I just have no idea about how this NVIM completion menu works in general let alone how and why it is different from vanilla vim behavior.
Hope to be helpful in this question one day.
