### ISSUE TITLE
Pressing undo broke something

### ISSUE THREAD

**Issue by JikkuJose** [SirVer/ultisnips#906] opened 2017-10-29 16:31 UTC
I expanded a trigger word (https://github.com/justinj/vim-react-snippets) & then pressed undo. This error showed up in quick fix.

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/jikkujose/.vim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/Users/jikkujose/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 342, in _cursor_moved
    self._csnippets[0].update_textobjects()
  File "/Users/jikkujose/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/_snippet_instance.py", line 80, in update_textobjects
    if obj._update(done):
  File "/Users/jikkujose/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/_viml_code.py", line 20, in _update
    self.overwrite(_vim.eval(self._code))
  File "/Users/jikkujose/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 128, in overwrite
    if self.current_text == gtext:
  File "/Users/jikkujose/.vim/plugged/ultisnips/pythonx/UltiSnips/text_objects/_base.py", line 101, in current_text
    return _vim.buf[self._start.line][self._start.col:self._end.col]
  File "/Users/jikkujose/.vim/plugged/ultisnips/pythonx/UltiSnips/_vim.py", line 25, in __getitem__
    rv = vim.current.buffer[idx]
  File "/usr/local/lib/python3.6/site-packages/neovim/api/buffer.py", line 45, in __getitem__
    return self.request('nvim_buf_get_lines', i, i + 1, True)[0]
  File "/usr/local/lib/python3.6/site-packages/neovim/api/common.py", line 44, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Index out of bounds'
```

**Comment by andreyorst** [comment] 2018-04-07 10:14
Seems like duplicate of #800. Fell fre to reopen if it is not.

**Closed by andreyorst** 2018-04-07 10:14 UTC
Labels: traceback
