### ISSUE TITLE
[bug] neovim : press F6, F7 or F8 .etc in insert mode, neovim will be stuck

### ISSUE THREAD

**Issue by MaiLunJiye** [SirVer/ultisnips#1245] opened 2020-06-16 14:47 UTC
**Expected behavior:** press F6 in insert mode, neovim work normally

**Actual behavior:** neovim will be struck.

**Steps to reproduce**

1. open a file
2. press i to insert mode, and type some chars.
3. press f6 in insert mode, then neovim will be stuck

-----

- **Operating System**: Linux archlinux 5.7.2-arch1-1
- **Vim Version**: **neovim** : NVIM v0.4.3  Build type: Release

- **UltiSnips Version**: e83c82099d9bd43dc7895e3cb5b114ee5a2a07c6

- **Python inside Vim**:  
```
No python2
python3 : 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50)                                                      
[GCC 7.5.0]
```

- **Docker repo/vimrc**: 

The plugin was managed by vim-plug

.config/nvim/init.vim
```
filetype off
call plug#begin("~/.nvim")
Plug 'SirVer/ultisnips' 
call plug#end()
```

**Comment by lacygoill** [comment] 2020-06-17 21:58
Duplicate of #1202, #1215, #1225, #1227, #1239.

Update pynvim so that it includes [this commit](https://github.com/neovim/pynvim/commit/3791b2581eac4d2f1a829ab6792a122a0bb914fc).

    pip install --user git+https://github.com/neovim/pynvim

**Comment by mutewinter** [comment] 2020-08-16 00:22
FYI you may need to `pip uninstall pynvim` before running the install above for this to work (due to caching, I'm sure).

**Closed** 2020-11-16 15:52 UTC
