### ISSUE TITLE
expand_anon with regex not working as expected when multiple happen in a row

### ISSUE THREAD

**Issue by bibli-alex** [SirVer/ultisnips#1121] opened 2019-11-01 02:22 UTC
Contains the same snippet as https://github.com/SirVer/ultisnips/issues/1115

**Expected behavior:**
Should input a dotpoint at the start of each line

**Actual behavior:**
The number used in the regex is placed at the start of the first line

**Steps to reproduce**
```
global !p
def create_dotpoint_placeholders(snip):
    try:
      placeholders_amount = int(snip.buffer[snip.line].strip())
    except:
      placeholders_amount = 1

    # erase current line
    snip.buffer[snip.line] = ''

    anon_snippet_body = ''
    for i in range(placeholders_amount):
      anon_snippet_body += '• ${' + str(i+1) + ':description}\n'

    # expand anonymous snippet
    snip.expand_anon(anon_snippet_body)
endglobal

post_jump "create_dotpoint_placeholders(snip)"
snippet "stnd\.(\d?)" "Adds dot-points" br
`!p snip.rv = match.group(1)`
endsnippet
```
Enter `stnd.2<expand hotkey>`. Go back to `normal` mode, and go below the newly created lines, and enter `stnd.4<expand hotkey>`. The first dot point of the second lot will be led with the number `4` instead of a dotpoint. 
See this gif for a demo: https://media.giphy.com/media/gLvDD4efXrVgVJllMH/source.gif

-----

- **Operating System**: Mac OS 10.5
- **Vim Version**: VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug  3 2019 18:05:22), macOS version, Included patches: 1-1800
- **UltiSnips Version**: `9b0d5fa4f756232cc0392706a5643a5b5148affd`
- **Python inside Vim**: No Python2, 3.7.4

**Comment by SirVer** [comment] 2019-12-22 19:50
Working as intended for me: https://asciinema.org/a/J8aCHJsjxBFKnLyhgeglJXAbr

Closing, since I cannot reproduce this.

**Closed by SirVer** 2019-12-22 19:50 UTC
