### ISSUE TITLE
UltiSnip not working when Macvim initially launched

### ISSUE THREAD

**Issue by pdoak** [SirVer/ultisnips#476] opened 2015-04-06 19:43 UTC
I am using UltiSnip with MacVim  and YouCompleteMe. When I initially launch MacVim, UltiSnip does not work but if I issue the command: `UltiSnipEdit`, it will then work

I have the following in my vimrc:

```
"UltiSnips
let g:UltiSnipsEditSplit="vertical"
" let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
"let g:UltiSnipsExpandTrigger="<c-tab>"

" From stackoverflow http://stackoverflow.com/questions/14896327/ultisnips-and-youcompleteme
function! g:UltiSnips_Complete()
    call UltiSnips#ExpandSnippet()
    if g:ulti_expand_res == 0
        if pumvisible()
            return "\<C-n>"
        else
            call UltiSnips#JumpForwards()
            if g:ulti_jump_forwards_res == 0
               return "\<TAB>"
            endif
        endif
    endif
    return ""
endfunction

au BufEnter * exec "inoremap <silent> " . g:UltiSnipsExpandTrigger . " <C-R>=g:UltiSnips_Complete()<cr>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsListSnippets="<c-e>"
" this mapping Enter key to <C-y> to chose the current highlight item 
" and close the selection list, same as other IDEs.
" CONFLICT with some plugins like tpope/Endwise
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

function! g:UltiSnips_Reverse()
  call UltiSnips#JumpBackwards()
  if g:ulti_jump_backwards_res == 0
    return "\<C-P>"
  endif
  return ""
endfunction
au BufEnter * exec "inoremap <silent> " . g:UltiSnipsJumpBackwardTrigger . " <C-R>=g:UltiSnips_Reverse()<cr>"
```

Any ideas as to why this is not working initially?

**Comment by SirVer** [comment] 2015-04-08 06:17
No idea. that sounds super strange. Can you check your `:verbose imap` for all ultisnips triggers on initial start?

**Comment by brunobeltran** [comment] 2015-04-20 17:21
I'm having a similar problem on both big windows build of vim and on my vim in Ubuntu. 

I can actually reproduce the (lack of) available snippets with a vimrc that just loads Vundle with itself and UltiSnips as the only plugins, with no other configuration.

When I add YouCompleteMe, it becomes clear that the error is actually that the filetype is not being correctly used to load in available snippets. That is, if I open a file, say test.py, and type
cla
nothing happens. But if I first do a 
    :UltiSnipsAddFileType python
    :UltiSnipsEdit
    <ctrl-o> " to return to prev buffer
then type
    cla
I get a complete menu with 
    class    <snip> ...
    clatin1  <snip> ...
    shotclass <snip> ....

**Comment by brunobeltran** [comment] 2015-04-20 17:28
With my full vimrc, my initial `:verbose imap` looks like
```
i  <C-N>       *@jedi#complete_string(0)
        Last set from ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
i  .           *@.<C-R>=jedi#complete_string(1)<CR>
        Last set from ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
i  <Nul>       * <C-X><C-O><C-P>
        Last set from ~/.vim/bundle/YouCompleteMe/autoload/youcompleteme.vim
i  <Up>        * pumvisible() ? "\<C-P>" : "\<Up>"
        Last set from ~/.vim/bundle/YouCompleteMe/autoload/youcompleteme.vim
i  <Down>      * pumvisible() ? "\<C-N>" : "\<Down>"
        Last set from ~/.vim/bundle/YouCompleteMe/autoload/youcompleteme.vim
i  <C-Tab>     * <C-R>=UltiSnips#ListSnippets()<CR>
        Last set from ~/.vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
i  <Plug>ISurround * <C-R>=<SNR>20_insert(1)<CR>
        Last set from ~/.vim/bundle/vim-surround/plugin/surround.vim
i  <Plug>Isurround * <C-R>=<SNR>20_insert()<CR>
        Last set from ~/.vim/bundle/vim-surround/plugin/surround.vim
i  <Plug>AlwaysEnd & <SNR>19_AlwaysEnd
        Last set from ~/.vim/bundle/vim-endwise/plugin/endwise.vim
i  <Plug>DiscretionaryEnd & <SNR>19_DiscretionaryEnd
        Last set from ~/.vim/bundle/vim-endwise/plugin/endwise.vim
i  <SNR>19_AlwaysEnd * <C-R>=<SNR>19_crend(1)<CR>
        Last set from ~/.vim/bundle/vim-endwise/plugin/endwise.vim
i  <SNR>19_DiscretionaryEnd * <C-R>=<SNR>19_crend(0)<CR>
        Last set from ~/.vim/bundle/vim-endwise/plugin/endwise.vim
i  <C-B>       * <Up>
        Last set from ~/.vim/config_basic.vim
i  <C-D>       * <Right><BS>
        Last set from ~/.vim/config_basic.vim
i  <C-F>       * <Right>
        Last set from ~/.vim/config_basic.vim
i  <C-G>S        <Plug>ISurround
        Last set from ~/.vim/bundle/vim-surround/plugin/surround.vim
i  <C-G>s        <Plug>Isurround
        Last set from ~/.vim/bundle/vim-surround/plugin/surround.vim
i  <Tab>       * pumvisible() ? "\<C-N>" : "\<Tab>"
        Last set from ~/.vim/bundle/YouCompleteMe/autoload/youcompleteme.vim
i  <NL>        * <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>
        Last set from ~/.vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
i  <CR>          <CR><Plug>DiscretionaryEnd
        Last set from ~/.vim/bundle/vim-endwise/plugin/endwise.vim
i  <C-S>         <Plug>Isurround
        Last set from ~/.vim/bundle/vim-surround/plugin/surround.vim
i  <C-X><CR>   & <CR><SNR>19_AlwaysEnd
        Last set from ~/.vim/bundle/vim-endwise/plugin/endwise.vim
i  |           * |<Esc>:call <SNR>7_align()<CR>a
        Last set from ~/.vimrc
```
after doing the magic to get the snips loaded, it looks identical.

**Comment by SirVer** [comment] 2015-04-22 04:24
Can you post your full vimrc? It sounds like ftdetect/ might not be sourced correctly. That is usually a problem with the wrong ordering of the commands for your plugin manager.

**Comment by brunobeltran** [comment] 2015-04-22 12:29
I'm posting the entire thing for purposes of being honest, but as you can see, everything but UltiSnips and the required lines to pull in Vundle are commented out. 

The problem is reproducible in this state.

```bbeltr1-lenovo:~
$ cat .vimrc
" Use Vundle for plugins

" This section must be first, and verbatim/as is
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
" some plugin or another that I use is assuming I'm in .vim
call vundle#rc('~/.vim/bundle')
" call vundle#begin()

"""""""""""""""
" ALL YOUR PLUGINS ARE BELONG TO ME
"""""""""""""""
" Indispensible plugins. Note that gmarik/vundle must come first!
" None of these set any nonstandard options by default
Bundle 'gmarik/vundle'
" Bundle 'tpope/vim-endwise'
" Bundle 'tpope/vim-git'
" Bundle 'tpope/vim-surround'
" Bundle 'tpope/vim-commentary'
" Bundle 'tpope/vim-repeat'
" Bundle 'tpope/vim-fugitive'
" Bundle 'scrooloose/syntastic'
" Bundle 'scrooloose/nerdtree'

" """"""""""""""
" " Now source non-external program dependent, non plugin dependent configs
" """""""""""""""
" source ~/.vim/config_basic.vim
" source ~/.vim/config_extended.vim

" """"""""""""""""
" " Now some plugins that need configuration
" """"""""""""""""
" " colors
" Plugin 'altercation/vim-colors-solarized'
" syntax enable
" set background=dark
" " let g:solarized_termcolors=256
" set t_Co=16
" colorscheme solarized
" " FUCK TMUX
" colorscheme desert

" " airline is special, usually requires patched fonts
" Plugin 'bling/vim-airline'
" let g:airline#extensions#tabline#enabled=1
" let g:airline_theme="luna"
" set laststatus=2
" "set encoding=utf-8
" "let g:airline_powerline_fonts = 1
" "set guifont=Fira\ Mono\ Medium\ for\ Powerline:h9

" " Easymotion
" Plugin 'Lokaltog/vim-easymotion'
" " remove <leader> to use for search by default
" map  <Leader>/ <Plug>(easymotion-sn)
" omap <Leader>/ <Plug>(easymotion-tn)
" vmap <Leader>/ <Plug>(easymotion-tn)
" map  <Leader>n <Plug>(easymotion-next)
" map  <Leader>N <Plug>(easymotion-prev)
" " avoid repeated hjkl input
" map <Leader><Leader>l <Plug>(easymotion-lineforward)
" map <Leader><Leader>j <Plug>(easymotion-j)
" map <Leader><Leader>k <Plug>(easymotion-k)
" map <Leader><Leader>h <Plug>(easymotion-linebackward)
" let g:EasyMotion_startofline = 0
" " smartcase is nice, so only match case if you include an uppercase letter
" let g:EasyMotion_smartcase = 1


" " ack, better version of grep
" " Plugin 'mileszs/ack.vim'


" " tabularize can be used to line up stuff based on regexes
" Plugin 'godlygeek/tabular'
" " here's a mapping to automatically alighn on | when typing cucumber tables
" " I'd like to extend this to align on & (but not on \&), and not in any "verbatim"
" " modes like verbatim or lstlisting.
" inoremap <silent> <Bar>   <Bar><Esc>:call <SID>align()<CR>a
" function! s:align()
"   let p = '^\s*|\s.*\s|\s*$'
"   if exists(':Tabularize') && getline('.') =~# '^\s*|' && (getline(line('.')-1) =~# p || getline(line('.')+1) =~# p)
"     let column = strlen(substitute(getline('.')[0:col('.')],'[^|]','','g'))
"     let position = strlen(matchstr(getline('.')[0:col('.')],'.*|\s*\zs.*'))
"     Tabularize/|/l1
"     normal! 0
"     call search(repeat('[^|]*|',column).'\s\{-\}'.repeat('.',position),'ce',line('.'))
"   endif
" endfunction


" " mad snippets, yo.
" " disabled for now, since it requires python, which I can't guarantee on
" " windows in any reasonable way
Plugin 'SirVer/ultisnips'
" Snippets are separated from the engine. Add this if you want them:
Plugin 'honza/vim-snippets'
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
" let g:UltiSnipsExpandTrigger="<c-x>"
" let g:UltiSnipsJumpForwardTrigger="<c-a>"
" let g:UltiSnipsJumpBackwardTrigger="<c-s>"
" If you want :UltiSnipsEdit to split your window.
" let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsSnippetsDir='~/.vim/UltiSnips'
let g:UltiSnipsSnippetDirectories=['UltiSnips']

" " Make a seamless interface with tmux
" " REQUIRES: extra config on tmux side
" " use custom bindings (same as defaults for now)
" Plugin 'christoomey/vim-tmux-navigator'
" let g:tmux_navigator_no_mappings = 1
" if has("win16") || has("win32")
"     nnoremap <silent> <C-S-h> :TmuxNavigateLeft<cr>
"     nnoremap <silent> <C-S-j> :TmuxNavigateDown<cr>
"     nnoremap <silent> <C-S-k> :TmuxNavigateUp<cr>
"     nnoremap <silent> <C-S-l> :TmuxNavigateRight<cr>
"     nnoremap <silent> <C-S-\> :TmuxNavigatePrevious<cr>
" elseif has("unix") || has("linux")
"     inoremap <silent> h  <Esc>:TmuxNavigateLeft<cr>
"     inoremap <silent> j  <Esc>:TmuxNavigateDown<cr>
"     inoremap <silent> k  <Esc>:TmuxNavigateUp<cr>
"     inoremap <silent>   <Esc>:TmuxNavigateRight<cr>
"     inoremap <silent>   <Esc>:TmuxNavigatePrevious<cr>
"     nnoremap <silent> h  :TmuxNavigateLeft<cr>
"     nnoremap <silent> j  :TmuxNavigateDown<cr>
"     nnoremap <silent> k  :TmuxNavigateUp<cr>
"     nnoremap <silent>   :TmuxNavigateRight<cr>
"     nnoremap <silent>   :TmuxNavigatePrevious<cr>
"     cnoremap <silent> h  <Esc>:TmuxNavigateLeft<cr>
"     cnoremap <silent> j  <Esc>:TmuxNavigateDown<cr>
"     cnoremap <silent> k  <Esc>:TmuxNavigateUp<cr>
"     cnoremap <silent>   <Esc>:TmuxNavigateRight<cr>
"     cnoremap <silent>   <Esc>:TmuxNavigatePrevious<cr>
" endif

" " Finally
" """""""""""""
" " omnicompletion/"intellisense
" """""""""""""
" set tags+=tags;$HOME

" " Baller addition to omnicompletion: JEDI-VIM
" Plugin 'davidhalter/jedi-vim'
" " i use <c-space> for changing keyboard langauges
" let g:jedi#completions_command = "<C-N>"
" " change this only if you really want to do everything manually
" let g:jedi#auto_initialization = 1
" " prevent it from being a bully
" let g:jedi#auto_vim_configuration = 0
" " i'd like it to only select the first option right away when I explicitly call it
" " since that option isn't present I'll disable it except for when I explicitly call it
" let g:jedi#popup_on_dot = 0
" " prevent dumb warning when I'm using an incompatible vim
" let g:jedi#squelch_py_warning = 1
" let g:jedi#force_py_version = 3

" " YOU COMPLETE ME
" Plugin 'Valloric/YouCompleteMe'
" let g:ycm_global_ycm_extra_conf = '~/.vim/ycm_extra_conf.py'

" "" YouCompleteMe
" let g:ycm_key_list_previous_completion=['<Up>']

" "" Ultisnips
" let g:UltiSnipsExpandTrigger="<c-j>"

" " function! g:UltiSnips_Complete()
" "     call UltiSnips#ExpandSnippet()
" "     if g:ulti_expand_res == 0
" "         if pumvisible()
" "             return "\<C-n>"
" "         else
" "             call UltiSnips#JumpForwards()
" "             if g:ulti_jump_forwards_res == 0
" "                return "\<TAB>"
" "             endif
" "         endif
" "     endif
" "     return ""
" " endfunction

" " au BufEnter * exec "inoremap <silent> " . g:UltiSnipsExpandTrigger . " <C-R>=g:UltiSnips_Complete()<cr>"
" " let g:UltiSnipsJumpForwardTrigger="<tab>"
" " let g:UltiSnipsListSnippets="<c-e>"
" " " this mapping Enter key to <C-y> to chose the current highlight item
" " " and close the selection list, same as other IDEs.
" " " CONFLICT with some plugins like tpope/Endwise
" " inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
'''

**Comment by SirVer** [comment] 2015-04-23 06:26
That config is broken - there is no vundle#end(). And I am pretty sure you need vundle#begin, not rc. Also you definitively need 

    filetype plugin indent on

after vundle end.

Please refer to the sample vimrc on https://github.com/gmarik/Vundle.vim. 

Closing this for now, please speak up if you have further trouble.

**Closed by SirVer** 2015-04-23 06:26 UTC
