### ISSUE TITLE
need an additional char to trigger snippets

### ISSUE THREAD

**Issue by alexwongdl** [SirVer/ultisnips#1073] opened 2019-04-11 03:37 UTC
My vim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct  3 2018 05:41:40)
macOS version
Included patches: 1-450
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
```
`SirVer/ultisnips` and `honza/vim-snippets` are installed in my vim and could work. however, if I want to trigger snippets I need to add at least one char (include space). 

For example:
![image](https://user-images.githubusercontent.com/8745241/55928843-cee69a80-5c4c-11e9-9967-d04b2e1692fc.png)

In this python script, I type in 'docs' and use <c-p> to trigger snippets, the prompt menu shows up, however, cannot expand as expected. 

![image](https://user-images.githubusercontent.com/8745241/55929157-086bd580-5c4e-11e9-8b06-23d9e2c8aaca.png)
If  I type in 'docs ' or 'docsa' or 'docsb...' or some codes like this, it will expand succeed.

**Comment by SirVer** [comment] 2019-10-30 19:50
That is a weird bug, no idea where that is coming from. Can you provide a minimal vimrc to trigger this?

**Comment by SirVer** [comment] 2019-11-19 20:01
I'd love to investigate, but I cannot reproduce with the given information. Closing.

**Closed by SirVer** 2019-11-19 20:01 UTC
Labels: pending feedback, triaged
