### ISSUE TITLE
nvim-lsp used with ultisnips becomes slow.

### ISSUE THREAD

**Issue by wgxh-cli** [SirVer/ultisnips#1378] opened 2021-08-10 10:36 UTC
I'm a neovim user, i use neovim 0.5;
When i used this plugin, then my neovim lsp becomes slow.
But i don't known why, only tsserver gets slow, other language servers still maintain original speed.

System: `archlinux`
Plugins related to completion:
1. nvim-compe.
2. nvim-lspconfig.
3. ultisnips.
4. vim-snippets.
Please tell me how to solve issue, thanks!

**Comment by SirVer** [comment] 2021-08-14 15:18
This is likely due to the decsion of NeoVim to run python out of process, this means that any interaction with UltiSnips is much, much slower. Please try to reproduce under vanilla Vim, if you cannot, I'll close this issue for reasons below.

This issue is marked as only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).

**Closed** 2021-08-15 05:53 UTC
Labels: pending feedback, neovim only
