### ISSUE TITLE
vim crashes with ultisnips enabled

### ISSUE THREAD

**Issue by amonks** [SirVer/ultisnips#771] opened 2016-10-14 00:53 UTC
I'm a long-time happy ultisnips user.

About an hour ago, vim crashed on me with the following error:

```
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'

Current thread 0x00007fff76203000 (most recent call first):
Vim: Caught deadly signal ABRT
Vim: Finished.
```

I can open vim, but as soon as I try to _insert text_, I get the error and crash.

I removed all my other plugins and cleared out my vimrc to the following:

```
set nocompatible

call plug#begin('~/.vim/bundle')
Plug 'SirVer/ultisnips'
call plug#end()
```

I still get the error. Remove ultisnips from my bundle directory and the error stops happening.

here's my `vim --version`:

```
[I] ➜  ~ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  9 2016 17:45:26)
MacOS X (unix) version
Included patches: 1-27
Compiled by travis@Traviss-Mac-592.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +find_in_path    -mouse_sysmouse  -tag_any_white
+arabic          +float           +mouse_urxvt     -tcl
+autocmd         +folding         +mouse_xterm     +termguicolors
+balloon_eval    -footer          +multi_byte      +terminfo
+browse          +fork()          +multi_lang      +termresponse
++builtin_terms  +fullscreen      -mzscheme        +textobjects
+byte_offset     -gettext         +netbeans_intg   +timers
+channel         -hangul_input    +num64           +title
+cindent         +iconv           +odbeditor       +toolbar
+clientserver    +insert_expand   +packages        +transparency
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl/dyn        +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        -X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
+file_in_path    +mouse_sgr       +tag_old_static  
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: clang   -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib  -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib   -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE
```

**Comment by muammar** [comment] 2016-10-23 12:18
I have been hit with this problem as well but in Linux. Having ultisnips enabled makes vim crash. I use neobundle, so commented the line that loads  this plugin and vim is not crashing anymore. Any possible solution for this?

**Comment by egryaznov** [comment] 2016-11-15 18:06
Same problem here.

**Comment by muammar** [comment] 2016-11-23 21:16
Today, **vim** was updated in **debian** to version `8.0.0095-1`, and activating back `NeoBundle 'SirVer/ultisnips'`, the problem is not there anymore.

**Comment by jasonlong** [comment] 2017-03-07 17:58
Started experiencing this same error this week on MacOS. Updated Homebrew recently, so maybe a problem with a newer Python version?

**Comment by dbmrq** [comment] 2017-03-09 02:57
I've had this problem more than once when updating MacVim with Homebrew. Uninstalling it and installing it all over again fixed it for some reason.

**Comment by jasonlong** [comment] 2017-03-09 15:38
Thanks @dbmrq, that worked for me. :thumbsup:

**Comment by olimorris** [comment] 2017-03-29 22:01
I am having this exact same issue. Uninstalled MacVim and it still appears. So weird. Any help would be appreciated

**Comment by kiryph** [comment] 2017-08-04 15:06
I had this issue as well: macvim switched to python3.6.2 and I still had python 3.6.1 installed. updating with `brew update python3` resolved this issue for me.

**Comment by tylerdooling** [comment] 2017-09-22 20:26
Same issue - `brew upgrade python3` worked for me as well.

**Comment by SirVer** [comment] 2018-04-01 20:47
This is what happens - Vim needs to link against Python at build time, but also dynamically loads Python at run time. If the version you linked against and the version you load at run time differs, things can crash.

This happens every time, brew decides to update python on Mac OS. It can also happen on Linux, depending how you get your vim packages. 

It is not an UltiSnips issue, so closing as answered.

**Closed by SirVer** 2018-04-01 20:47 UTC

**Comment by kiryph** [comment] 2018-04-02 06:28
### Note for MacVim.dmg and Homebrew User on macOS: Pin Python Version

You can run into a problem of non-matching python versions either when upgrading MacVim but also by running brew upgrades. In particular, python might be a dependence of another homebrew formula. This means you want to upgrade something different and homebrew also upgrades python without your intention.

I would highly recommend to pin your python version in homebrew when using MacVim downloaded as a dmg from http://macvim-dev.github.io/macvim/ (macvim.org).

```
$ brew pin python
$ brew list --pinned
python
ruby
```
