### ISSUE TITLE
Snippet behaviour changes with trigger string

### ISSUE THREAD

**Issue by SimonMandlik** [SirVer/ultisnips#1217] opened 2020-05-01 16:22 UTC
I encountered following behaviour when trying to define my own snippets for LaTeX. The MWE is below:

```
snippet bm "" iA
\bm{$1}${0}
endsnippet

snippet mxx "" iA
\bm{$1}${0}
endsnippet

snippet myy "" iA
\bm{$1}${0}
endsnippet

snippet mzz "" iA
\bm{ $1 }${0}
endsnippet
```

Out of the first three snippets, only the first one works as intended. The second and third get expanded incorrectly, even though the definition is exactly the same apart from a trigger string. I believe this is due the trigger string starting with `m`. Weirdly enough, fourth snippet works after adding spaces around brackets.

**Expected behavior:**

`trigger` -> `\bm{<cursor>}<jump>` for first three snippets

**Actual behavior:**

`trigger` -> `\bm{<cursor>}<jump>` for the first one
`trigger` -> `mxx<cursor>}<jump>` for the second one
`trigger` -> `myy<cursor>}<jump>` for the third one

**Steps to reproduce**

.vimrc:

```
" Bootstrap Plug
let autoload_plug_path = stdpath('data') . '/site/autoload/plug.vim'
if !filereadable(autoload_plug_path)
  silent execute '!curl -fLo ' . autoload_plug_path . '  --create-dirs 
      \ "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
unlet autoload_plug_path

call plug#begin(stdpath('data') . '/plugged')

Plug 'Valloric/YouCompleteMe'
Plug 'SirVer/ultisnips'
Plug 'lervag/vimtex'

let g:tex_flavor='latex'

call plug#end()
```

-----

- **Operating System**: Mac OS 10.15.4
- **Vim Version**: NVIM v0.4.3, Build type: Release
- **UltiSnips Version**: ee31ea1c7d08ced8577120b4c1d55c5a05351a75
- **Python inside Vim**: 3.7.7

**Comment by SirVer** [comment] 2021-03-02 10:13
I do not have vimtex installed and I am not using NVIm, but vanilla Vim. For me all snippets work as expected: https://asciinema.org/a/rBibecYsaZhhoIbg9WuVVtmDM

I assume that this is (yet another) neovim incompatibility problem. Closing as such.

This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).

**Closed by SirVer** 2021-03-02 10:13 UTC
