### ISSUE TITLE
Error while using VIM

### ISSUE THREAD

**Issue by dannyboy990** [SirVer/ultisnips#1185] opened 2020-03-05 10:50 UTC
I've installed Python 3.6 and made sure it is in vim's path.

I receive a weird error while in insert mode trying to write any character:
Error detected while processing function UltiSnips#TrackChange:
Could not load library function PySlice_AdjustIndices
![2020-03-05 (1)](https://user-images.githubusercontent.com/61826135/75974591-c0961280-5edf-11ea-83da-1780309c96d6.png)

**Comment by paulnorthup** [comment] 2020-03-05 15:48
I also get an error on every keystroke in insert mode
<img width="696" alt="Screen Shot 2020-03-05 at 10 48 30 AM" src="https://user-images.githubusercontent.com/114175/75998445-e0710a80-5ece-11ea-811b-1064e5e8a78c.png">

**Comment by SirVer** [comment] 2020-03-09 13:52
@dannyboy990 This error indicates that your Python installation is broken. Try `vim -u NONE`, then inside Vim try `:py3 import sys; print(sys.version)` and see if that works.

@paulnorthup Your problem seems to be that UltiSnips does not properly load. The interesting error is the first keystroke, but it is very likely that this is also a Python problem.

I cannot repro either of these problems with the provided information, therefore will close this as non-actionable.

**Closed** 2020-03-09 13:53 UTC
Labels: can't reproduce

**Comment by tunaboy** [comment] 2024-01-04 03:30
Not sure if this is the issue, but I had the same behaviour, and I was able to reproduce it.  In the interests of helping  fools similar to myself, my issue was that when I'd compiled vim myself, I had _not_ added the magic  args to configure:

    ./configure --enable-python3interp --with-python3-command=python3 

This was obvious when I did the vim --version, and it came back with -python3...  

Once I compiled, and saw the +python3, the issue went away.  This was vim 9.1.3, but I think I've been in this situation earlier, just didn't get documented.

I'm sure this is documented (that you need to have vim with +python3), but the symptom and cause was not clear when I upgraded my vim on this system, and re-encountered the issue.

Feel free to delete this, but I think it might help others.  (and thank you for ultisnips, it's become an essential for me, obviously!)
