### ISSUE TITLE
UltiSnips reading from snippets directory despite correct UltiSnipsSnippetDirectories

### ISSUE THREAD

**Issue by ykonstant1** [SirVer/ultisnips#1040] opened 2018-12-12 18:05 UTC
I installed UltiSnips on Mint 18.3 via Vundle together with vim-snippets; my goal is to use it to edit tex files.  Navigating to ~/.vim/bundle/vim-snippets/snippets/ I found tex.snippets which had many default snippets.  I tested them and they worked fine.

However, when I tried to define my own snippets via UltiSnipsEdit while editing a tex file, the resulting snippet was not called.  I looked for known issues and found the issue concerning directory names.  So I added ~/UltiSnips to the runtimepath and inserted 
let g:UltiSnipsSnippetDirectories = ['~/UltiSnips', '~/.vim/ultisnips']
to my .vimrc.

However, this did not do the trick at all.  To test this, I navigated around vim-snippets and found more tex.snippets files in that directory with other snippets, none of which worked.  Somehow, the only tex.snippets file that was recognized by UltiSnips was the one in ~/.vim/bundle/vim-snippets/snippets/tex.snippets.

As a further test, I copied the tex.snippets file from that folder to ~/SnipUtils and removed vim-snippets from vim (with Vundle).  Then no snippets worked at all.  I could still call UltiSnipsEdit, it still edited the tex.snippets file from the ~/SnipUtils folder, but when I saved, exited and edited a tex file, no snippet worked.

**Expected behavior:**
For instance: 

vim new.tex
:UltiSnipsEdit
snippet foyo
test
endsnippet
:w 
:q 
vim new.tex
foyo<tab> (tab is my expander, it worked fine on snippets from ~/.vim/bundle/vim-snippets/snippets/tex.snippets)
output: test

**Actual behavior:**

When calling a snippet from ~/.vim/bundle/vim-snippets/snippets/tex.snippets, the expected behaviour occurs.  When calling a custom snippet, or a snippet defined in, say, ~/.vim/bundle/vim-snippets/UltiSnips/tex.snippets, nothing happens.

Minimal .vimrc:

set nocompatible              
filetype off                  

 set rtp+=~/.vim/bundle/Vundle.vim
 call vundle#begin()

 Plugin 'VundleVim/Vundle.vim'

 Plugin 'tpope/vim-fugitive'

 Plugin 'git://git.wincent.com/command-t.git'

 Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

Plugin 'kana/vim-textobj-user'
Plugin 'rbonvall/vim-textobj-latex'
Plugin 'lervag/vimtex'
" Track the engine.
Plugin 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
"Plugin 'honza/vim-snippets'

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let UltiSnipsJumpForwardTrigger = "<tab>"
let UltiSnipsJumpBackwardTrigger = "<s-tab>"

let g:UltiSnipsEditSplit="vertical"

 call vundle#end()            " required
 filetype plugin indent on    " required

set backspace=indent,eol,start

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  set undofile		" keep an undo file (undo changes after closing)
endif
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching

map Q gq

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  filetype plugin indent on

  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  autocmd BufReadPost *
    \ if line("'\"") >= 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

else

  set autoindent		" always set autoindenting on

endif " has("autocmd")

if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

packadd matchit
set winaltkeys=no
set guifont=Roboto\ Mono\ 12
:command C let @/=""
:set number
let g:tex_flavor='latex'
 let g:Tex_ViewRule_pdf =  'zathura'

set runtimepath+=~/UltiSnips
let g:UltiSnipsSnippetDirectories = ['~/UltiSnips', '~/.vim/ultisnips']

-----
- **Operating System**: Linux Mint 18.3 
- **Vim Version**: 7.4 
- **UltiSnips Version**: 3.1
                              run: `git rev-parse origin/master` -->
- **Python inside Vim**: 2.7.12 / Unclear; the command below returns the command is not available in this version for py3.
- **Docker repo/vimrc**:

**Comment by lacygoill** [comment] 2019-01-07 00:34
Your `vimrc` is too long, and relies on a plugin manager. Try to reproduce with a minimal `vimrc`, with simple `:set rtp` statements, instead of Vundle:

    set rtp^=/path/to/ultisnips/
    set rtp+=/path/to/ultisnips/after/

Also:

- What's the absolute path to the file where you write your tex snippets?
- what's the filetype of your `.tex` file, as reported by `:echo &ft`?
- What's the output of `:echo g:UltiSnipsSnippetDirectories`?
- What's an example of snippet which doesn't work?

Try this:

    :let g:UltiSnipsSnippetDirectories=["UltiSnips"]
    :let g:tex_flavor = 'latex'

Or this:

    :let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']
    :let g:tex_flavor = 'latex'

And write your snippet in `~/.vim/UltiSnips/tex.snippets`.

For more information, see `:h UltiSnips-how-snippets-are-loaded`.

**Comment by SirVer** [comment] 2019-11-09 23:26
This is very likely a dupe of #711. Closing as duplicate.

**Closed by SirVer** 2019-11-09 23:26 UTC
