### ISSUE TITLE
unassigned function keys (F1 - F12) freeze nvim in insert mode

### ISSUE THREAD

**Issue by dstadelm** [SirVer/ultisnips#1202] opened 2020-04-06 13:03 UTC
**Expected behavior:**
When in insert mode accidentally pressing F1-F12 nothing should happen

**Actual behavior:**
nvim freezes

**Steps to reproduce**
Empty .vimrc with UltiSnips installed through minpac

1. Install UltiSnips
2. Open nvim
3. Change to insert mode
4. Press an unassigned function key (F1-F12)

**Workaround**
inoremap &lt;Fxx&gt; &lt;Nop&gt;

-----

- **Operating System**: Ubuntu 19.04
- **Vim Version**: nvim v0.4.3
- **UltiSnips Version**: ee31ea1c7d08ced8577120b4c1d55c5a05351a75
- **Python inside Vim**: 3.7.5 (default, Nov 20 2019, 09:21:52) [GCC 9.2.1 20191008]

**Comment by lacygoill** [comment] 2020-04-09 06:19
I can reproduce without UltiSnips:

    nvim -u NONE -i NONE +'au InsertCharPre * exe "py3 import vim" | py3 vim.eval("v:char")'

Not sure, but it could be a bug in Nvim.  I reported [the issue](https://github.com/neovim/neovim/issues/12095) on their bug tracker.

---

It happens because of this autocmd: https://github.com/SirVer/ultisnips/blob/ee31ea1c7d08ced8577120b4c1d55c5a05351a75/plugin/UltiSnips.vim#L21

Which runs `vim.eval("v:char")`: https://github.com/SirVer/ultisnips/blob/ee31ea1c7d08ced8577120b4c1d55c5a05351a75/pythonx/UltiSnips/snippet_manager.py#L880

For the moment, one solution is to disable the autotrigger feature on startup:

    if has('nvim')
        au VimEnter * if exists('#UltiSnips_AutoTrigger')
            \ |     exe 'au! UltiSnips_AutoTrigger'
            \ |     aug! UltiSnips_AutoTrigger
            \ | endif
    endif

You can still toggle it manually via a mapping; example:

    nno <silent> cou :<c-u>call s:ultisnips_toggle_autotrigger()<cr>

    fu s:ultisnips_toggle_autotrigger() abort
        if exists('#UltiSnips_AutoTrigger')
            au! UltiSnips_AutoTrigger
            aug! UltiSnips_AutoTrigger
            echom '[UltiSnips AutoTrigger] OFF'
        else
            augroup UltiSnips_AutoTrigger
                au!
                au InsertCharPre,TextChangedI,TextChangedP * call UltiSnips#TrackChange()
            augroup END
            echom '[UltiSnips AutoTrigger] ON'
        endif
    endfu

Note that as long as the feature is enabled, you'll face the issue whenever you press a function key in insert mode.

**Comment by dstadelm** [comment] 2020-04-09 08:59
Thanks a lot, that was blazing fast!

**Comment by tomtomjhj** [comment] 2020-04-09 15:19
@dstadelm please test https://github.com/neovim/pynvim/pull/439.

**Comment by lacygoill** [comment] 2020-04-10 04:44
https://github.com/neovim/pynvim/pull/439 fixes the issue on my machine.

For anyone who wants to test on their machine, try to run these shell commands:

    git clone https://github.com/neovim/pynvim
    cd pynvim
    git remote add upstream git://github.com/neovim/pynvim.git
    git fetch upstream pull/439/head:unicode_errors
    git checkout unicode_errors
    pip3 install .

This should update pynvim to use the PR mentioned earlier.

**Comment by dstadelm** [comment] 2020-04-10 05:58
> @dstadelm please test [neovim/pynvim#439](https://github.com/neovim/pynvim/pull/439).

This indeed fixes the issue! Thanks for your incredible fast reply!

**Comment by SirVer** [comment] 2020-04-10 09:08
@lacygoill Fantastic work! Thanks for digging in here!

Closing as this has nothing to do with UltiSnips.

**Closed by SirVer** 2020-04-10 09:08 UTC
