### ISSUE TITLE
Repeated mirrors reduced to one copy

### ISSUE THREAD

**Issue by pelonpelon** [SirVer/ultisnips#439] opened 2015-02-09 03:37 UTC
I'm trying to write a snippet collection to help in the creation of vim plugins.
```
snippet sk "syntax keyword definition" b
syntax keyword ${1:`!p snip.rv = snip.basename`}${2:Keyword} ${3:a keyword}
highlight link $1$2 $2
$0
endsnippet
```
When the snippet is invoked all mirrors seem to be working.
If the user accepts the defaults everything works fine.
If the user changes ```${1:`!p snip.rv = snip.basename`}``` all is good.

When `${2:Keyword}` is changed by the user
`$1$2 $2` becomes `$1$2`

If I separate ```${1: `!p snip.rv = snip.basename`}${2:Keyword}``` by a space or character
```${1:`!p snip.rv = snip.basename`}``` ```${2:Keyword}```
everything works as expected. 

I tried to mix tabstops and python t[2] but no luck.
I tried creating a concatenated string in python but even `t[1]t[2] t[2]` becomes `t[1]t[2]` 

My hack for now is to force an underscore between tabstops
```${1:`!p snip.rv = snip.basename`}_${2:Keyword}```

But this seems like a bug

**Comment by SirVer** [comment] 2015-02-09 06:08
This is a duplicate of https://github.com/SirVer/ultisnips/issues/158. The problem is that if $2 is reduced to zero characters and you type again, UltiSnips is confused if you want to append the characters to $1 or add to $2 - here it is deciding for $1 and keeps $2 empty.

**Comment by SirVer** [comment] 2015-02-09 06:08
Closing as dup.

**Closed by SirVer** 2015-02-09 06:08 UTC
