### ISSUE TITLE
UltiSnips not completing

### ISSUE THREAD

**Issue by Exalaber** [SirVer/ultisnips#848] opened 2017-04-28 15:11 UTC
I installed UltiSnips using vundle, and it seemed to work at first. I was able to use UltiSnipsEdit to create cpp.snips, and write a snippet. When I could not activate that snippet, I discovered that cpp.snips was stored in a folder called ultisnips in the directory local to the file I was editing. I moved cpp.snips to ~/.vim/bundle/ultisnips and added  let g:UltiSnipsSnippetDirectories = ['~/.vim/bundle/ultisnips', 'ultisnips']  to my .vimrc and after that I was able to get the file with my test snippet using UltiSnipsEdit. However, it still would not expand the snippet. I have tried remapping the trigger two different ways  let g:UltiSnipsExpandTrigger='<c-e>'  and  inoremap <Tab> <c-r>=UltiSnips#ExpandSnippet()<cr> , neither of them have worked. It does not seem to be a file type detection issue because my syntax highlighting still works, and UltiSnipsEdit came up with the correct file name. I have looked around these issues and tried many of the workarounds for similar problems.

This repository contains the result of vim --version and my current .vimrc
https://github.com/Exalaber/vim-info

**Comment by sudavid4** [comment] 2017-05-02 08:41
I'm having the same problem here

**Comment by TimothyBramlett** [comment] 2017-05-13 16:35
I am having the same problem.  Did anyone ever resolve this?

**Comment by andreyorst** [comment] 2018-04-06 10:41
Please read https://github.com/SirVer/ultisnips/issues/956#issuecomment-377816395

duplicate of #948

**Closed by andreyorst** 2018-04-06 10:41 UTC
