### ISSUE TITLE
Ultisnips CursorMoved function clash with Unite plugin

### ISSUE THREAD

**Issue by petobens** [SirVer/ultisnips#578] opened 2015-10-03 04:27 UTC
I recently noticed a clash between Unite and Ultisnips which freezes vim. I thought it was a Unite issue (actually an issue with one Unite source, neomru.) but when I reported the issue [there](https://github.com/Shougo/neomru.vim/issues/27#issuecomment-145188708) I was told that it was an Ultisnips problem:

>Reproduced. But it is not neomru/unite bug.
If I disable UltiSnips#CursorMoved() function, it works.
It is UltiSnips bug. Closing.

In the linked issue there is minimal vimrc and steps to reproduce. Thanks in advance for the help.

**Comment by Shougo** [comment] 2015-10-04 00:37
@petobens It is not crash.  It seems infinite loop in UltiSnips.

**Comment by SirVer** [comment] 2015-10-04 12:27
This is a duplicate of https://github.com/SirVer/ultisnips/issues/155 and similar to https://github.com/sirver/ultisnips/issues/510.

The problem is that UltiSnips need to understand changes of the buffer, so it runs a diff of the buffer on each cursor move as long as a snippet is active. Unite brings up a new buffer without informing UltiSnips (i.e. not firing an autocommand). UltiSnips is confused about that, believes it is the same buffer with many changes and runs the diff. This is `O(n^3)`. It will not run forever, but for a very, very long time if the new buffer is long.

Possible fixes are that Unite fires the autocommand BufLeave or BufEnter. Alternatively, a workaround can be added into UltiSnips [here](https://github.com/SirVer/ultisnips/blob/master/pythonx/UltiSnips/snippet_manager.py#L370), similar to the fix for #510. But I do not know how that workaround might look.

@Shougo, can you advise how to detect that I am now jumping into a unite buffer?

**Comment by petobens** [comment] 2015-10-04 16:17
Thanks @Sirver for the explanation. I hope @Shougo can shed a light on this.

**Comment by Shougo** [comment] 2015-10-05 13:59
> @Shougo, can you advise how to detect that I am now jumping into a unite buffer?

I think you can detect it by filetype check.
Unite buffer is filetype "unite".

**Comment by SirVer** [comment] 2015-10-12 05:34
@petobens Can you try out to exit the snippet when ft=unite?

**Comment by petobens** [comment] 2015-10-14 13:08
Hi @SirVer , adding:

```py
        _vim.command('autocmd Filetype unite call UltiSnips#LeavingBuffer()')
```
indeed solves the issue.

**Comment by SirVer** [comment] 2015-10-17 12:50
No, that should be the correct solution here. Your snippets are exciting once you enter any unite buffer. Thanks for testing this!

**Closed** 2015-10-17 12:50 UTC

**Comment by petobens** [comment] 2015-10-17 13:58
Thank you!
