### ISSUE TITLE
Ctrl+R <tab> not showing regex snippets

### ISSUE THREAD

**Issue by kurkale6ka** [SirVer/ultisnips#427] opened 2015-01-16 10:27 UTC
Hi,

Apologies if this has already been raised.
These are my puppet snippets:
```
clearsnippets                                
                                             
snippet 'source|///' "Static" r              
source => 'puppet:///modules/${1:module}/$2',
endsnippet                                   
                                             
snippet 'content|template' "Template" r      
content => template('${1:module}/$2.erb'),   
endsnippet                                   
                                             
snippet case "Case"                          
case \$${1:fact} {                           
  ${2:attr1}: {$3}                           
  ${4:attr2}: {$5}                           
  default: { fail("$6") }                    
}                                            
endsnippet                                   
                                             
snippet case "Selector"                      
\$${1:var} = \$${2:fact} ? {                 
  ${3:attr1} => ${4:val1},                   
  ${5:attr2} => ${6:val2},                   
  default => $7,                             
}                                            
endsnippet                                   
                                             
snippet if                                   
if $1 {                                      
  $2                                         
}                                            
endsnippet                                   
                                             
snippet p                                    
package { '$1':                              
  $2                                         
}                                            
endsnippet                                   
```
As per the title, when using `Ctrl+R<tab>`, all snippets appear in the list a part from `snippet 'source|///' ` and `snippet 'content|template'`

**Comment by SirVer** [comment] 2015-01-16 18:03
duplicate of https://github.com/SirVer/ultisnips/issues/177

**Closed by SirVer** 2015-01-16 18:03 UTC
