### ISSUE TITLE
Why I got UnicodeEncodeError?

### ISSUE THREAD

**Issue by AttufliX** [SirVer/ultisnips#433] opened 2015-02-01 09:44 UTC
I typed "inc" and then trigger ultisnips by <c-j> (because I also use YouCompleteMe binding <tab> already) to complete it to """"include "a.h" """", and strangely, after I typed "h" and I got such error:

UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-15: ordinal n
ot in range(128).

I have compile vim with python2 intergration, I don't know wether I need compile vim with python3 instead or not.

**Comment by AttufliX** [comment] 2015-02-01 09:47
Oh, sorry for my poor knowledge about markdown. I said I trigger ultisnips by CTRL-J because I have YouCompleteMe plugin which has binded with TAB KEY.

**Comment by SirVer** [comment] 2015-02-01 09:48
No, should work with python2 - that is how I use it. Do you have any non-ascii characters in your file? Can you put your vim config someplace?

**Comment by AttufliX** [comment] 2015-02-01 13:43
I don't type any non-ascii characters in the file.

Config about Ultisnip in my vimrc file is shown as below: 

let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-b>"

Strangely this problem occurs only when I type "inc" and get "include "XXX" ", but it works fine when 
typing "Inc" and get "include <XXX> ".

I guess the problem may be due to the conflict with YouCompleteMe, because it seems that YCM's pop-up completion menu is always ready to pop up. But the problem only shows up in few situations like what I have described above, so I am still confused.

**Comment by AttufliX** [comment] 2015-02-01 13:49
I don't type any non-ascii characters in the file.

Config about Ultisnip in my vimrc file is shown as below:

let g:UltiSnipsExpandTrigger="`<C-J>`"
let g:UltiSnipsJumpForwardTrigger="`<C-J>`"
let g:UltiSnipsJumpBackwardTrigger="`<C-B>`"

Strangely this problem occurs only when I type "inc" and get "include "XXX" ", but it works fine when 
typing "Inc" and get "include `<XXX>`".

I guess the problem may be due to the conflict with YouCompleteMe, because it seems that YCM's pop-up completion menu is always ready to pop up. But the problem only shows up in few situations like what I have described above, so I am still confused.

**Comment by SirVer** [comment] 2015-02-02 12:42
I am using YCM too and I cannot reproduce this problem. Are you sure that you are using the shipped `inc` snippet and have not added one of your own that might contain non-unicode characters? Change the snippet to contain the same content as the `Inc` snippet for testing and see what happens.

**Comment by SirVer** [comment] 2015-02-16 06:10
no answer -> closing.

**Closed by SirVer** 2015-02-16 06:10 UTC
