### ISSUE TITLE
ImportError: cannot import name 'vim_helper'

### ISSUE THREAD

**Issue by JohnRama** [SirVer/ultisnips#1303] opened 2020-12-18 21:12 UTC
Hi, 
I'm trying to setup the ultisnips in my environment.
Added following line into my .vimrc

	NeoBundle 'SirVer/ultisnips'
	NeoBundle 'honza/vim-snippets'

	let g:UltiSnipsExpandTrigger = "<tab>"
	let g:UltiSnipsJumpForwardTrigger = "<tab>"
	let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

Then having a error whenever trying to write some character into the file.
Problem happens at the following line.

ultisnips/autoload/UltiSnips.vim 
	py3 from UltiSnips import UltiSnips_Manager

it seems "vim_helper" import error happens at snipmate.py.
There is vim_helper.py at ultisnips/pythonx/UltiSnips/ directory.
vim_helper is imported by multiple files including
snippet_manager.py, which seems to import vim_helper successfully.
Wondering why this happens....

Any clue ?
Thanks for the help. 
John Rama

**Expected behavior:**

	no error

**Actual behavior:**

	error with following messages

	- Error log
		"python.vim" 34L, 664C
		Traceback (most recent call last):
			File "<string>", line 1, in <module>
			File "/usr/lib/python3.4/imp.py", line 245, in load_module
				return load_package(name, filename)
			File "/usr/lib/python3.4/imp.py", line 217, in load_package
				return methods.load()
			File "/home/atmark/.vim/bundle/ultisnips/pythonx/UltiSnips/__init__.py", line 6, in
		<module>
				from UltiSnips.snippet_manager import UltiSnips_Manager
			File "/home/atmark/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line
		 13, in <module>
				from UltiSnips import vim_helper
			File "/home/atmark/.vim/bundle/ultisnips/pythonx/UltiSnips/vim_helper.py", line 10,
		in <module>
				from UltiSnips.snippet.source.file.common import normalize_file_path
			File "/home/atmark/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/__init__.p
		y", line 8, in <module>
				from UltiSnips.snippet.source.file.snipmate import SnipMateFileSource
			File "/home/atmark/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/snipmate.py", line 9, in <module>
				from UltiSnips import vim_helper
		ImportError: cannot import name 'vim_helper'

**Steps to reproduce**

	1. put the followings into .vimrc

		NeoBundle 'SirVer/ultisnips'
		NeoBundle 'honza/vim-snippets'

		let g:UltiSnipsExpandTrigger = "<tab>"
		let g:UltiSnipsJumpForwardTrigger = "<tab>"
		let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

	2. Try to edit the file with vim or 
		 type following commands
		:py3 from UltiSnips import UltiSnips_Manager

**Operating System**: 
	- debian 8.3

**Vim Version**: 
	VIM - Vi IMproved 8.2 

**UltiSnips Version**:
	$git rev-parse origin/master
	e6478871c04bb75f3c6cb9b90e171fffbf9c8ff3

**Python inside Vim**: 
	:py3 print(sys.version)
	3.4.2

**Comment by JohnRama** [comment] 2020-12-22 16:13
Just update. 

By using the tag "3.2", the problem was gone.
This problem starts happening after following commits.

fed56f1 Normalize all paths before returning them (#1159)

**Comment by SirVer** [comment] 2020-12-24 21:18
No idea why that particular commit should start triggering these errors. Main comment here is that python 3.4 is very old and no longer supported by UltiSnips, maybe the problem stems from there? 

Closing, as I cannot reproduce this problem.

**Closed by SirVer** 2020-12-24 21:18 UTC
