### ISSUE TITLE
Segmentation Fault - potential python issue?

### ISSUE THREAD

**Issue by badeleux** [SirVer/ultisnips#980] opened 2018-05-02 21:01 UTC
**Expected behavior:**
Use VIM with UltiSnips

**Actual behavior:**
```
Vim: Caught deadly signal SEGV
Vim: Finished.
zsh: segmentation fault
```

**Steps to reproduce**
brew install vim
/usr/local/bin/vim
_type char_

-----

- **Operating System**: Mac OS 10.13.3
- **Vim Version**: VIM - 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 24 2018 05:16:21)
macOS version
Included patches: 1-1750
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               +ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -D_DARWIN_C_SOURCE -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.2/lib/perl5/5.26.2/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation  -lruby.2.5.1 -lobjc
```

- **UltiSnips Version**: 
- **Python inside Vim**:
3.6.5 (default, Apr 25 2018, 14:23:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
- **System python**:
```
$ which python
/usr/local/bin/python
$ python
Python 3.6.5 (default, Apr 25 2018, 14:23:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
```

Both system and vim use same python 3.6.5

**Comment by badeleux** [comment] 2018-05-03 06:19
Vim doesn't crash when running inside lldb

**Comment by andreyorst** [comment] 2018-05-03 06:57
Sorry I can't repro this, cause I don't have Mac, or Hackintosh installed. I believe @SirVer is running Mac Os, maybe he can help. 

Possible duplicate of #771

**Comment by badeleux** [comment] 2018-05-03 07:50
Installed neovim and works without issues.

**Comment by andreyorst** [comment] 2018-05-03 08:06
However please note that neovim [isn't properly supported](https://github.com/SirVer/ultisnips/issues?utf8=%E2%9C%93&q=label%3A%22neovim+only%22)

**Comment by sbromberger** [comment] 2018-11-07 20:33
Ref #1032 - not just OSX.

**Closed** 2018-11-08 19:57 UTC
Labels: osx only, possible bug
