### ISSUE TITLE
ultisnips only loads all.snippets

### ISSUE THREAD

**Issue by VdeVatman** [SirVer/ultisnips#580] opened 2015-10-04 07:25 UTC
This problem only happens to me when I've got YCM, if I change it with neocomplete UltiSnips loads the right snippets.

**Comment by VdeVatman** [comment] 2015-10-04 10:20
After lot of test, the only thing that I can see that changes the snippets being loaded is this line:

`let g:UltiSnipsSnippetDirectories=["ultisnipsnippets", "UltiSnips"]`

If I change it for: 

`let g:UltiSnipsSnippetDirectories="UltiSnips"`

It just doesn't load any snippets.

**Comment by SirVer** [comment] 2015-10-04 12:36
Similar to https://github.com/SirVer/ultisnips/issues/530, https://github.com/SirVer/ultisnips/issues/243, https://github.com/SirVer/ultisnips/issues/264.

It means your `ftdetect/UltiSnips.vim` is not sourced. That means your vundle install is busted. Go back to the minimal vundle `.vimrc` and go from there. It is likely that `syntax on`, `filetype on/off`, `set nocompatible` ordering is messed up. 

> let g:UltiSnipsSnippetDirectories="UltiSnips"

this is just wrong. do not change this line.

I am closing this until you can repro with a minimal vundle `.vimrc`, I highly doubt this is an UltiSnips bug.

**Comment by VdeVatman** [comment] 2015-10-04 21:17
with a minimal vundle .vimrc happens the same:

```
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Track the engine.
Plugin 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
Plugin 'honza/vim-snippets'

" YCM
Plugin 'Valloric/YouCompleteMe'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
```

**Comment by SirVer** [comment] 2015-10-06 07:14
Okay, let's dig a little deeper. Why do you have YCM there? For a minimal repro case it is not needed. Also, if you use YCM you have a tab-key conflict ([see here](http://stackoverflow.com/a/18685821/200945)).

When you open `/tmp/blub.py`, what is `:set filetype` reporting? What is `:verbose imap <your expand trigger>` reporting? Is `lorem<your expand trigger>` expanding the lorem ipsum snippet from all.snippets? is `class<your expand trigger>` expanding the class snippet from python.snippets?

**Comment by SirVer** [comment] 2015-10-12 05:34
ping?

**Comment by VdeVatman** [comment] 2015-10-16 06:12
Pong ,

Sorry I needed something "functional" to work with and stuck with neosnippet a few days, now I'm here again seeing what could be failing here. I created a new user with an empty home directory and installed vundle in there, then copied the .vimrc just written in there and installed YCM following these commands:

```
cd ~/.vim/bundle/YouCompleteMe
./install.py
cd ~
mkdir ycm_build
cd ycm_build
cmake -G "Unix Makefiles" . ~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp
cmake --build . --target ycm_support_libs
```

My ~/.vimrc is now: 

```
set nocompatible              " be iMproved, required
filetype off                  " required

"" YouCompleteMe
let g:ycm_key_list_previous_completion=['<Up>']

"" Ultisnips
let g:UltiSnipsExpandTrigger="<c-tab>"
let g:UltiSnipsListSnippets="<c-s-tab>"

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Track the engine.
Plugin 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
Plugin 'honza/vim-snippets'

" YCM
Plugin 'Valloric/YouCompleteMe'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

```
I did then: 

```
vim 
:BundleInstall 
```

And then tried what you've said, the results were:

> When you open /tmp/blub.py, what is :set filetype reporting? 
It is reporting: `filetype=python`

> What is :verbose imap <your expand trigger> reporting? 
It is reporting `C-Tab>     * <C-R>=UltiSnips#ExpandSnippet()<CR>`

> Is lorem<your expand trigger> expanding the lorem ipsum snippet from all.snippets? 
It shows with YCM but it doesn't expand

> is class<your expand trigger> expanding the class snippet from python.snippets? 
It doesn't even show the autocompletion for that snippet from `/tmp/blub.py`

Additionaly  if I type `:UltiSnipsEdit` from `/tmp/blub.py` it takes me to `~/.vim/UltiSnips/python.snippets` which is a working symlink to `~/.vim/bundle/vim-snippets/UltiSnips/python.snipptes` .

**Comment by SirVer** [comment] 2015-10-16 06:57
Quick thought: could it be that your terminal emulator is not forwarding ctrl+tab? Few do. 

Test if it works in gvim.

**Comment by VdeVatman** [comment] 2015-10-16 07:06
Yes, I remapped it to <C-j> and it expands fine now, but the snippet's autocompletion doesn't work when using YCM , it works when using NeoComplete though, I don't know why could it happen.

**Comment by SirVer** [comment] 2015-10-17 12:42
> Any ideas of why this happen?

No. If only the all.snippets is loaded that is usually an indication that `ftdetect/UltiSnips.vim` is not properly sourced. But since it works in general, just not for YCM I have no idea, sorry :(. Note that regular expression snippets are never autocompleted - maybe that is the case here? Let's summon @Valloric, maybe he has an idea?

> And is there a huge difference between YCM and NeoComplete?

I only use YCM, so I cannot tell you.

**Comment by SirVer** [comment] 2015-10-29 06:47
I am sorry, I cannot offer any more insights into this issue. I cannot reproduce it, neither on Linux or Mac OS. I feel it might be an YCM issue, though that seems strange too as UltiSnips apparently finds the snippets, they just do not end up with YCM. 

Closing for now, as I cannot make any more progress. If it still is disturbing you, could you open an issue with YCM and link this here?

**Closed by SirVer** 2015-10-29 06:47 UTC
Labels: user_question
