### ISSUE TITLE
Expanding a second snippet while the first tabstop of a snippet is selected that spans $0 crashes.

### ISSUE THREAD

**Issue by ches** [SirVer/ultisnips#450] opened 2015-02-26 23:24 UTC
I'm using current UltiSnips and vim-snippets (at time of writing, UltiSnips 56ac14840f and honza/vim-snippets@931af65f344b), and UltiSnips seems to be exploding somewhere in parsing the default Snipmate snippets for Rust. Here's how I can reproduce it repeatably:
1. `vim /tmp/test.rs`
2. Enter the trigger `let` and expand it.
3. Leave the first tabstop unchanged and attempt to move to the next one.

As soon as I jump to the second tabstop, I get the backtrace below. It seems like the error isn't with the `let` snippets specifically, I've tried removing those Snipmate snippets and replacing them with different UltiSnips versions with the same trigger, and I still get the exception. If I nuke all the Snipmate Rust snippets entirely, the problem goes away. Strange (?) that the error occurs not on initial expansion but on jumping to the second tabstop; I'll try to narrow down further exactly what in the Snipmate file seems to be causing a problem, but for now here's the backtrace.

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/ches/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "/Users/ches/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 144, in expand_or_jump
    rv = self._try_expand()
  File "/Users/ches/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 584, in _try_expand
    self._do_snippet(snippet, before)
  File "/Users/ches/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 553, in _do_snippet
    self._cs.find_parent_for_new_to(start), start, end)
  File "/Users/ches/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 240, in launch
    self.instantiate(snippet_instance, initial_text, indent)
  File "/Users/ches/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/snipmate.py", line 21, in instantiate
    parse_and_instantiate(snippet_instance, initial_text, indent)
  File "/Users/ches/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/parsing/snipmate.py", line 44, in parse_and_instantiate
    _create_mirrors(all_tokens, seen_ts)
  File "/Users/ches/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/parsing/snipmate.py", line 30, in _create_mirrors
    Mirror(parent, seen_ts[token.number], token)
KeyError: 0
```

**Comment by ches** [comment] 2015-02-26 23:43
So the problem snippet is this one:

```
snippet typ
	type ${1:NewName} = $0;
```

since the `let` snippet's default value for its first tabstop leaves the cursor sitting at the token "typ":

```
snippet let
       let ${1:name: type} = ${2};
```

Simply changing the snippet's trigger to `type` fixes the problem (and I personally prefer that trigger anyway...), but I suppose UltiSnips should at least have a better failure mode in this scenario?

**Comment by SirVer** [comment] 2015-02-28 11:05
Excellent bug report. I could not reproduce this at first because I have jumping and expanding bound to different keys. But If I expand -> expand I can reproduce the error. Thanks for reporting.

I agree about typ -> type. Wanna send a pull request to vim-snippets?

**Comment by ches** [comment] 2015-02-28 20:58
> I could not reproduce this at first because I have jumping and expanding bound to different keys.

Aha. By now I probably should have given in to occasional overloading pains and adopted that myself, but old habits die hard :smile: 

> I agree about typ -> type. Wanna send a pull request to vim-snippets?

Sure, I'm doing some other cleanup and additions to Rust snippets while I'm at it, I'll send a PR over there when ready and reference this issue.

**Comment by SirVer** [comment] 2015-07-11 16:36
Can still reproduce in 324a4f8ffc491b05346c284fcbbb6f77318d6b82.

**Comment by andreyorst** [comment] 2018-04-07 14:42
>1. vim /tmp/test.rs
>2. Enter the trigger let and expand it.
>3. Leave the first tabstop unchanged and attempt to move to the next one.

Can't reproduce in 1546022088a06e2f10e6e18aca842bcc1fd95116

**Comment by SirVer** [comment] 2018-04-07 16:14
Andrey, do you not have permission to close issues? If we cannot repro, we can’t do anything. No point in keeping it open.

**Comment by andreyorst** [comment] 2018-04-07 17:05
@SirVer I can. I've already closed 20 or more. I thought that i closed it. Weird.

**Closed by andreyorst** 2018-04-07 17:05 UTC
Labels: bug: snipmate only, can't reproduce
